# Getting metadata for Nanostring and RNA-seq data (excluding those from EGA)
This notebooks will collect the available metadata from GEO (or downloaded from the Supplementary material) along with Grace's metadata collected from previous analyses.

Author: Hope Townsend

In [2]:
library(data.table)
library(ggplot2)
library(stringr)
library(GEOquery)
library(rentrez)
library(tidyverse)

## 1. Read in metadata provided by Grace

In [6]:
grace_meta <- fread("~/Downloads/PrePostNACT_Normalized.csv", sep=",")
#colnames(grace_meta)
# don't need counts info
grace_meta <- grace_meta[,c("PRE SAMPLE ID", "POST SAMPLE ID", "Source", "Age", "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_32928797", "OS", "Death")]
grace_meta[1:2,]

  PRE SAMPLE ID
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
  POST SAMPLE ID                             Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55   8  1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
  PFS_high Chemo_status PFS_high_32928797 OS Death
1 0        1            0                 44 1
2 1        2            1                 51 0

## 2. James - Nanostring

In [7]:
# get the metadata to split into Pre and Post
GSE="GSE201600"
gset <- getGEO(GSE, GSEMatrix =TRUE, getGPL=T)
gset <- gset[[1]]

Found 1 file(s)

GSE201600_series_matrix.txt.gz

Using locally cached version: /var/folders/dp/zmpkfc9n3yld16sv5nhc1x5c0000gn/T//RtmphQsUjZ/GSE201600_series_matrix.txt.gz

Using locally cached version of GPL27956 found here:
/var/folders/dp/zmpkfc9n3yld16sv5nhc1x5c0000gn/T//RtmphQsUjZ/GPL27956.soft.gz

In [8]:
phenodf <- pData(gset)
colnames(phenodf)
phenodf[1:2,]
table(phenodf[["description"]])
table(phenodf[["data_processing"]])
table(phenodf[["histology:ch1"]])
table(phenodf[["age:ch1"]])
table(phenodf[["platinum-free interval:ch1"]])
table(phenodf[["progression status as of 4/25/22:ch1"]])
table(phenodf[["Sex:ch1"]])
table(phenodf[["Stage:ch1"]])
table(phenodf[["tissue:ch1"]])

metadata = phenodf[,c("geo_accession", "source_name_ch1",  "title", 'age:ch1', 
                      "histology:ch1", "platinum-free interval:ch1", "progression status as of 4/25/22:ch1", 
                     "Sex:ch1", "Stage:ch1", "tissue:ch1", "supplementary_file")]
dim(metadata)
unique(metadata$title)

 [1] "title"
 [2] "geo_accession"
 [3] "status"
 [4] "submission_date"
 [5] "last_update_date"
 [6] "type"
 [7] "channel_count"
 [8] "source_name_ch1"
 [9] "organism_ch1"
[10] "characteristics_ch1"
[11] "characteristics_ch1.1"
[12] "characteristics_ch1.2"
[13] "characteristics_ch1.3"
[14] "characteristics_ch1.4"
[15] "characteristics_ch1.5"
[16] "characteristics_ch1.6"
[17] "treatment_protocol_ch1"
[18] "molecule_ch1"
[19] "extract_protocol_ch1"
[20] "label_ch1"
[21] "label_protocol_ch1"
[22] "taxid_ch1"
[23] "hyb_protocol"
[24] "scan_protocol"
[25] "description"
[26] "data_processing"
[27] "platform_id"
[28] "contact_name"
[29] "contact_email"
[30] "contact_department"
[31] "contact_institute"
[32] "contact_address"
[33] "contact_city"
[34] "contact_state"
[35] "contact_zip/postal_code"
[36] "contact_country"
[37] "supplementary_file"
[38] "data_row_count"
[39] "Sex:ch1"
[40] "Stage:ch1"
[41] "age:ch1"
[42] "histology:ch1"
[43] "platinum-free interval:ch1"
[44] "progression status as of 4/25/22:ch1"
[45] "tissue:ch1"

           title                     geo_accession status
GSM6068308 Post patient 1 [Sample 1] GSM6068308    Public on Sep 28 2022
GSM6068309 Post patient 2 [Sample 2] GSM6068309    Public on Sep 28 2022
           submission_date last_update_date type channel_count
GSM6068308 Apr 26 2022     Sep 28 2022      RNA  1
GSM6068309 Apr 26 2022     Sep 28 2022      RNA  1
           source_name_ch1                          organism_ch1
GSM6068308 primary high grade serous ovarian cancer Homo sapiens
GSM6068309 primary high grade serous ovarian cancer Homo sapiens
           characteristics_ch1                              ... contact_country
GSM6068308 tissue: primary high grade serous ovarian cancer ... USA
GSM6068309 tissue: primary high grade serous ovarian cancer ... USA
           supplementary_file
GSM6068308 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6068nnn/GSM6068308/suppl/GSM6068308_20210707_30102572880322-01_Sample12_12.RCC.gz
GSM6068309 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6068nnn/GSM6068309/suppl/GSM6068309_20210709_30102572870322-01_Sample12_12.RCC.gz
           data_row_count Sex:ch1 Stage:ch1 age:ch1
GSM6068308 750            female  IIIC      69
GSM6068309 750            female  IIIC      62
           histology:ch1                    platinum-free interval:ch1
GSM6068308 high grade serous ovarian cancer 16
GSM6068309 high grade serous ovarian cancer 14
           progression status as of 4/25/22:ch1
GSM6068308 yes
GSM6068309 yes
           tissue:ch1
GSM6068308 primary high grade serous ovarian cancer
GSM6068309 primary high grade serous ovarian cancer

low count genes were filtered out for a total of 750 genes detected on the panel
                                                                              62

The resulting data file in RCC format was used for data analysis in the nCounter Advanced Analysis Software. Raw data in RCC format was uploaded to nSolver for automated normalization, background subtraction, and quality control (QC) check.
                                                                                                                                                                                                                                              62

high grade serous ovarian cancer
                              62

46 49 50 53 54 55 56 59 60 61 62 63 64 66 68 69 70 71 72 75 76 79
 2  2  2  2  2  2  2  2  2  2  2 10  2  2  4  6  2  4  4  2  2  2

 1 10 11 12 14 16 17 19  2 24 26 31 39  4  5  6  7  8  9
 2  6  2  2  4  2  4  2  6  4  2  2  2  4  4  4  6  2  2

 no yes
  8  54

female
    62

IIIA IIIB IIIC   IV
   2    6   46    8

       primary high grade serous ovarian cancer
                                             31
primary high grade serous ovarian cancer biopsy
                                             31

[1] 62 11

 [1] "Post patient 1 [Sample 1]"   "Post patient 2 [Sample 2]"
 [3] "Post patient 3 [Sample 3]"   "Post patient 4 [Sample 4]"
 [5] "Post patient 5 [Sample 5]"   "Post patient 6 [Sample 6]"
 [7] "Post patient 7 [Sample 7]"   "Post patient 8 [Sample 8]"
 [9] "Post patient 9 [Sample 9]"   "Post patient 10 [Sample 10]"
[11] "Post patient 11 [Sample 11]" "Post patient 12 [Sample 12]"
[13] "Post patient 13 [Sample 13]" "Post patient 14 [Sample 14]"
[15] "Post patient 15 [Sample 15]" "Post patient 16 [Sample 16]"
[17] "Post patient 17 [Sample 17]" "Post patient 18 [Sample 18]"
[19] "Post patient 19 [Sample 19]" "Post patient 20 [Sample 20]"
[21] "Post patient 21 [Sample 21]" "Post patient 22 [Sample 22]"
[23] "Post patient 23 [Sample 23]" "Post patient 24 [Sample 24]"
[25] "Post patient 25 [Sample 25]" "Post patient 26 [Sample 26]"
[27] "Post patient 27 [Sample 27]" "Post patient 28 [Sample 28]"
[29] "Post patient 29 [Sample 29]" "Post patient 30 [Sample 30]"
[31] "Post patient 31 [Sample 31]" "Pre patient 1 [Sample 32]"
[33] "Pre patient 2 [Sample 33]"   "Pre patient 3 [Sample 34]"
[35] "Pre patient 4 [Sample 35]"   "Pre patient 5 [Sample 36]"
[37] "Pre patient 6 [Sample 37]"   "Pre patient 7 [Sample 38]"
[39] "Pre patient 8 [Sample 39]"   "Pre patient 9 [Sample 40]"
[41] "Pre patient 10 [Sample 41]"  "Pre patient 11 [Sample 42]"
[43] "Pre patient 12 [Sample 43]"  "Pre patient 13 [Sample 44]"
[45] "Pre patient 14 [Sample 45]"  "Pre patient 15 [Sample 46]"
[47] "Pre patient 16 [Sample 47]"  "Pre patient 17 [Sample 48]"
[49] "Pre patient 18 [Sample 49]"  "Pre patient 19 [Sample 50]"
[51] "Pre patient 20 [Sample 51]"  "Pre patient 21 [Sample 52]"
[53] "Pre patient 22 [Sample 53]"  "Pre patient 23 [Sample 54]"
[55] "Pre patient 24 [Sample 55]"  "Pre patient 25 [Sample 56]"
[57] "Pre patient 26 [Sample 57]"  "Pre patient 27 [Sample 58]"
[59] "Pre patient 28 [Sample 59]"  "Pre patient 29 [Sample 60]"
[61] "Pre patient 30 [Sample 61]"  "Pre patient 31 [Sample 62]"

In [9]:
# get an easier set
metadata$Patient <- paste0("P", str_split_fixed(metadata$title, " ", 4)[,3])
metadata$Treatment_status <- str_split_fixed(metadata$title, " ", 4)[,1]
metadata$count_name <- str_split_fixed(str_split_fixed(metadata$supplementary_file, ".gz", 2)[,1], "suppl/", 2)[,2]
metadata$Name <- paste0(metadata$Patient, "_", metadata$Treatment_status)

In [10]:
metadata[31:63,c("geo_accession", "Patient", "count_name", "Treatment_status", "age:ch1", "Sex:ch1", "Stage:ch1", "Name")]

           geo_accession Patient
GSM6068338 GSM6068338    P31
GSM6068339 GSM6068339    P1
GSM6068340 GSM6068340    P2
GSM6068341 GSM6068341    P3
GSM6068342 GSM6068342    P4
GSM6068343 GSM6068343    P5
GSM6068344 GSM6068344    P6
GSM6068345 GSM6068345    P7
GSM6068346 GSM6068346    P8
GSM6068347 GSM6068347    P9
GSM6068348 GSM6068348    P10
GSM6068349 GSM6068349    P11
GSM6068350 GSM6068350    P12
GSM6068351 GSM6068351    P13
GSM6068352 GSM6068352    P14
GSM6068353 GSM6068353    P15
GSM6068354 GSM6068354    P16
GSM6068355 GSM6068355    P17
GSM6068356 GSM6068356    P18
GSM6068357 GSM6068357    P19
GSM6068358 GSM6068358    P20
GSM6068359 GSM6068359    P21
GSM6068360 GSM6068360    P22
GSM6068361 GSM6068361    P23
GSM6068362 GSM6068362    P24
GSM6068363 GSM6068363    P25
GSM6068364 GSM6068364    P26
GSM6068365 GSM6068365    P27
GSM6068366 GSM6068366    P28
GSM6068367 GSM6068367    P29
GSM6068368 GSM6068368    P30
GSM6068369 GSM6068369    P31
NA         NA            NA
           count_name
GSM6068338 GSM6068338_20220217_30102684530922-01_Sample08_08.RCC
GSM6068339 GSM6068339_20210709_30102572870322-01_Sample06_06.RCC
GSM6068340 GSM6068340_20210709_30102572870322-01_Sample03_03.RCC
GSM6068341 GSM6068341_20210709_30102572870322-01_Sample04_04.RCC
GSM6068342 GSM6068342_20210709_30102572870322-01_Sample08_08.RCC
GSM6068343 GSM6068343_20210707_30102572880322-01_Sample03_03.RCC
GSM6068344 GSM6068344_20210707_30102572880322-01_Sample01_01.RCC
GSM6068345 GSM6068345_20210707_30102572880322-01_Sample10_10.RCC
GSM6068346 GSM6068346_20210707_30102572880322-01_Sample02_02.RCC
GSM6068347 GSM6068347_20210707_30102572880322-01_Sample06_06.RCC
GSM6068348 GSM6068348_20210709_30102572870322-01_Sample09_09.RCC
GSM6068349 GSM6068349_20210707_30102572880322-01_Sample04_04.RCC
GSM6068350 GSM6068350_20210709_30102572870322-01_Sample11_11.RCC
GSM6068351 GSM6068351_20220224_30102684540922-01_Sample03_03.RCC
GSM6068352 GSM6068352_20220224_30102684540922-01_Sample02_02.RCC
GSM6068353 GSM6068353_20220216_30102684500922-01_Sample09_09.RCC
GSM6068354 GSM6068354_20220217_30102684530922-01_Sample01_01.RCC
GSM6068355 GSM6068355_20220204_30102684520922-01_Sample01_01.RCC
GSM6068356 GSM6068356_20220217_30102684530922-01_Sample02_02.RCC
GSM6068357 GSM6068357_20220216_30102684500922-01_Sample06_06.RCC
GSM6068358 GSM6068358_20220216_30102684500922-01_Sample03_03.RCC
GSM6068359 GSM6068359_20220204_30102684520922-01_Sample09_09.RCC
GSM6068360 GSM6068360_20220224_30102684540922-01_Sample05_05.RCC
GSM6068361 GSM6068361_20220204_30102684520922-01_Sample05_05.RCC
GSM6068362 GSM6068362_20220216_30102684500922-01_Sample01_01.RCC
GSM6068363 GSM6068363_20220216_30102684500922-01_Sample05_05.RCC
GSM6068364 GSM6068364_20220216_30102684500922-01_Sample11_11.RCC
GSM6068365 GSM6068365_20220224_30102684540922-01_Sample07_07.RCC
GSM6068366 GSM6068366_20220204_30102684520922-01_Sample02_02.RCC
GSM6068367 GSM6068367_20220204_30102684520922-01_Sample04_04.RCC
GSM6068368 GSM6068368_20220217_30102684530922-01_Sample07_07.RCC
GSM6068369 GSM6068369_20220217_30102684530922-01_Sample11_11.RCC
NA         NA
           Treatment_status age:ch1 Sex:ch1 Stage:ch1 Name
GSM6068338 Post             49      female  IIIC      P31_Post
GSM6068339 Pre              69      female  IIIC      P1_Pre
GSM6068340 Pre              62      female  IIIC      P2_Pre
GSM6068341 Pre              54      female  IIIC      P3_Pre
GSM6068342 Pre              69      female  IIIC      P4_Pre
GSM6068343 Pre              71      female  IIIC      P5_Pre
GSM6068344 Pre              68      female  IIIC      P6_Pre
GSM6068345 Pre              63      female  IIIB      P7_Pre
GSM6068346 Pre              66      female  IIIC      P8_Pre
GSM6068347 Pre              56      female  IV        P9_Pre
GSM6068348 Pre              60      female  IIIC      P10_Pre
GSM6068349 Pre              70      female  IIIC      P11_Pre
GSM6068350 Pre              63      female  IIIC      P12_Pre
GSM6068351 Pre              63      female  IIIC      P13_Pre
GSM6068352 Pre              64      female  IIIC      P14_Pre
GSM6068353 Pre              53      female  IIIC      P15_Pre
GSM6068354 Pre              68      female  IIIC      P16_Pre
GSM6068355 Pre              71      female  IIIC      P17_Pre
GSM6068356 Pre              63      female  IV        P18_Pre
GSM6068357 Pre              75      female  IIIC      P19_Pre
GSM6068358 Pre              46      female  IV        P20_Pre
GSM6068359 Pre              69      female  IV        P21_Pre
GSM6068360 Pre              61      female  IIIA      P22_Pre
GSM6068361 Pre              72      female  IIIB      P23_Pre
GSM6068362 Pre              72      female  IIIC      P24_Pre
GSM6068363 Pre              59      female  IIIC      P25_Pre
GSM6068364 Pre              63      female  IIIC      P26_Pre
GSM6068365 Pre              50      female  IIIC      P27_Pre
GSM6068366 Pre              55      female  IIIC      P28_Pre
GSM6068367 Pre              79      female  IIIC      P29_Pre
GSM6068368 Pre              76      female  IIIB      P30_Pre
GSM6068369 Pre              49      female  IIIC      P31_Pre
NA         NA               NA      NA      NA        NA

In [ ]:
colnames(metadata)
metadata[1:4,]
colnames(metadata) <- c("GEO_accession", "disease", "title", "age", "histology", "PFI_mth", "progression_status_4.25.22", "Sex", "Stage", "tissue", "supplementary_file", "Patient", "Treatment_status", "count_name", "Name")

write.table(metadata[,c("GEO_accession", "disease", "title", "age", "histology", "PFI_mth", "progression_status_4.25.22", "Stage", "Patient", "Treatment_status", "Name")], 
            "../James_GSE201600/data/James_GSE201600_clean_metadata_11.5.24.txt", quote=FALSE, sep="\t", row.names=FALSE)

 [1] "geo_accession"
 [2] "source_name_ch1"
 [3] "title"
 [4] "age:ch1"
 [5] "histology:ch1"
 [6] "platinum-free interval:ch1"
 [7] "progression status as of 4/25/22:ch1"
 [8] "Sex:ch1"
 [9] "Stage:ch1"
[10] "tissue:ch1"
[11] "supplementary_file"
[12] "Patient"
[13] "Treatment_status"
[14] "count_name"
[15] "Name"

           geo_accession source_name_ch1
GSM6068308 GSM6068308    primary high grade serous ovarian cancer
GSM6068309 GSM6068309    primary high grade serous ovarian cancer
GSM6068310 GSM6068310    primary high grade serous ovarian cancer
GSM6068311 GSM6068311    primary high grade serous ovarian cancer
           title                     age:ch1 histology:ch1
GSM6068308 Post patient 1 [Sample 1] 69      high grade serous ovarian cancer
GSM6068309 Post patient 2 [Sample 2] 62      high grade serous ovarian cancer
GSM6068310 Post patient 3 [Sample 3] 54      high grade serous ovarian cancer
GSM6068311 Post patient 4 [Sample 4] 69      high grade serous ovarian cancer
           platinum-free interval:ch1 progression status as of 4/25/22:ch1
GSM6068308 16                         yes
GSM6068309 14                         yes
GSM6068310 24                         yes
GSM6068311 9                          yes
           Sex:ch1 Stage:ch1 tissue:ch1
GSM6068308 female  IIIC      primary high grade serous ovarian cancer
GSM6068309 female  IIIC      primary high grade serous ovarian cancer
GSM6068310 female  IIIC      primary high grade serous ovarian cancer
GSM6068311 female  IIIC      primary high grade serous ovarian cancer
           supplementary_file
GSM6068308 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6068nnn/GSM6068308/suppl/GSM6068308_20210707_30102572880322-01_Sample12_12.RCC.gz
GSM6068309 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6068nnn/GSM6068309/suppl/GSM6068309_20210709_30102572870322-01_Sample12_12.RCC.gz
GSM6068310 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6068nnn/GSM6068310/suppl/GSM6068310_20210709_30102572870322-01_Sample07_07.RCC.gz
GSM6068311 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6068nnn/GSM6068311/suppl/GSM6068311_20210709_30102572870322-01_Sample05_05.RCC.gz
           Patient Treatment_status
GSM6068308 P1      Post
GSM6068309 P2      Post
GSM6068310 P3      Post
GSM6068311 P4      Post
           count_name                                            Name
GSM6068308 GSM6068308_20210707_30102572880322-01_Sample12_12.RCC P1_Post
GSM6068309 GSM6068309_20210709_30102572870322-01_Sample12_12.RCC P2_Post
GSM6068310 GSM6068310_20210709_30102572870322-01_Sample07_07.RCC P3_Post
GSM6068311 GSM6068311_20210709_30102572870322-01_Sample05_05.RCC P4_Post

In [12]:
# have metadata be in format for  PRE & Post

metadat_wide <- metadata %>%
  pivot_wider(
    id_cols = c(Patient, age, PFI_mth, progression_status_4.25.22, Sex, Stage),
    names_from = Treatment_status,
    values_from = count_name,
    names_prefix = "",
    names_glue = "{Treatment_status}_count_name"
  )
metadat_wide[1:4,]

  Patient age PFI_mth progression_status_4.25.22 Sex    Stage
1 P1      69  16      yes                        female IIIC
2 P2      62  14      yes                        female IIIC
3 P3      54  24      yes                        female IIIC
4 P4      69  9       yes                        female IIIC
  Post_count_name
1 GSM6068308_20210707_30102572880322-01_Sample12_12.RCC
2 GSM6068309_20210709_30102572870322-01_Sample12_12.RCC
3 GSM6068310_20210709_30102572870322-01_Sample07_07.RCC
4 GSM6068311_20210709_30102572870322-01_Sample05_05.RCC
  Pre_count_name
1 GSM6068339_20210709_30102572870322-01_Sample06_06.RCC
2 GSM6068340_20210709_30102572870322-01_Sample03_03.RCC
3 GSM6068341_20210709_30102572870322-01_Sample04_04.RCC
4 GSM6068342_20210709_30102572870322-01_Sample08_08.RCC

### 2B. Add the metadata from Grace

In [13]:
#metadata[1:2,]
#grace_meta[1:2,]

matched_grace_meta <- grace_meta[grace_meta[["PRE SAMPLE ID"]] %in% metadata$count_name | grace_meta[["POST SAMPLE ID"]] %in% metadata$count_name,]
#matched_grace_meta[1:4,]
dim(matched_grace_meta)
#metadata[1:2,]

metadat_wide <- merge(metadat_wide, matched_grace_meta[,c("POST SAMPLE ID", "Source", "Age", "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_32928797", "OS", "Death")], by.x=c("Post_count_name"), by.y=c("POST SAMPLE ID"))

[1] 31 11

In [14]:
metadat_wide$Name_Source <- "James"
metadat_wide[1:4,]

  Post_count_name                                       Patient age PFI_mth
1 GSM6068308_20210707_30102572880322-01_Sample12_12.RCC P1      69  16
2 GSM6068309_20210709_30102572870322-01_Sample12_12.RCC P2      62  14
3 GSM6068310_20210709_30102572870322-01_Sample07_07.RCC P3      54  24
4 GSM6068311_20210709_30102572870322-01_Sample05_05.RCC P4      69  9
  progression_status_4.25.22 Sex    Stage
1 yes                        female IIIC
2 yes                        female IIIC
3 yes                        female IIIC
4 yes                        female IIIC
  Pre_count_name                                        Source        Age PFS
1 GSM6068339_20210709_30102572870322-01_Sample06_06.RCC PMID:36131935 69  16
2 GSM6068340_20210709_30102572870322-01_Sample03_03.RCC PMID:36131935 61  14
3 GSM6068341_20210709_30102572870322-01_Sample04_04.RCC PMID:36131935 54  24
4 GSM6068342_20210709_30102572870322-01_Sample08_08.RCC PMID:36131935 69   9
  Recurrence PFS_high Chemo_status PFS_high_32928797 OS Death Name_Source
1 1          1        2            NA                NA NA    James
2 1          1        2            NA                NA NA    James
3 1          1        2            NA                NA NA    James
4 1          0        1            NA                NA NA    James

### 2C. Get the counts to use comparable names

In [15]:
raw_counts <- fread("../James_GSE201600//data/counts/nsolver_raw_counts_11.5.24.txt")
raw_counts[1:5,]
colnames(raw_counts)
# replace Surgeny with Surgery (typo on their part)
just_raw_counts = raw_counts[,12:ncol(raw_counts)]
colnames(just_raw_counts)
raw_counts = raw_counts[,1:11]

  Probe Name Annotation Accession #    NS Probe ID Class Name Analyte Type
1 A2M        NA         NM_000014.4    NA          Endogenous mRNA
2 ACVR1C     NA         NM_145259.2    NA          Endogenous mRNA
3 ADAM12     NA         NM_003474.5    NA          Endogenous mRNA
4 ADGRE1     NA         NM_001256252.1 NA          Endogenous mRNA
5 ADM        NA         NM_001124.2    NA          Endogenous mRNA
  % Samples above Threshold Positive Flag Avg Count Min Count ...
1 100.00                    FALSE         1444.65   109       ...
2  87.10                    FALSE           30.85     8       ...
3 100.00                    FALSE          181.61    20       ...
4  59.68                    FALSE           14.94     4       ...
5 100.00                    FALSE          103.37    17       ...
  GSM6068360_20220224_30102684540922-01_Sample05_05.RCC
1 1146
2   14
3  167
4   11
5   47
  GSM6068361_20220204_30102684520922-01_Sample05_05.RCC
1 1974
2  110
3  305
4   12
5  101
  GSM6068362_20220216_30102684500922-01_Sample01_01.RCC
1 205
2  17
3  41
4   4
5  34
  GSM6068363_20220216_30102684500922-01_Sample05_05.RCC
1 1485
2    9
3  104
4    9
5   54
  GSM6068364_20220216_30102684500922-01_Sample11_11.RCC
1 899
2  29
3 785
4   6
5 122
  GSM6068365_20220224_30102684540922-01_Sample07_07.RCC
1 784
2   8
3 241
4   4
5  84
  GSM6068366_20220204_30102684520922-01_Sample02_02.RCC
1 898
2  24
3 282
4  13
5 120
  GSM6068367_20220204_30102684520922-01_Sample04_04.RCC
1 620
2  34
3 214
4   9
5  46
  GSM6068368_20220217_30102684530922-01_Sample07_07.RCC
1 1096
2   32
3  194
4   15
5   56
  GSM6068369_20220217_30102684530922-01_Sample11_11.RCC
1 2143
2   23
3  109
4   24
5   78

 [1] "Probe Name"
 [2] "Annotation"
 [3] "Accession #"
 [4] "NS Probe ID"
 [5] "Class Name"
 [6] "Analyte Type"
 [7] "% Samples above Threshold"
 [8] "Positive Flag"
 [9] "Avg Count"
[10] "Min Count"
[11] "Max Count"
[12] "GSM6068308_20210707_30102572880322-01_Sample12_12.RCC"
[13] "GSM6068309_20210709_30102572870322-01_Sample12_12.RCC"
[14] "GSM6068310_20210709_30102572870322-01_Sample07_07.RCC"
[15] "GSM6068311_20210709_30102572870322-01_Sample05_05.RCC"
[16] "GSM6068312_20210707_30102572880322-01_Sample11_11.RCC"
[17] "GSM6068313_20210707_30102572880322-01_Sample09_09.RCC"
[18] "GSM6068314_20210707_30102572880322-01_Sample07_07.RCC"
[19] "GSM6068315_20210707_30102572880322-01_Sample05_05.RCC"
[20] "GSM6068316_20210709_30102572870322-01_Sample01_01.RCC"
[21] "GSM6068317_20210709_30102572870322-01_Sample02_02.RCC"
[22] "GSM6068318_20210709_30102572870322-01_Sample10_10.RCC"
[23] "GSM6068319_20210707_30102572880322-01_Sample08_08.RCC"
[24] "GSM6068320_20220216_30102684500922-01_Sample08_08.RCC"
[25] "GSM6068321_20220224_30102684540922-01_Sample04_04.RCC"
[26] "GSM6068322_20220217_30102684530922-01_Sample09_09.RCC"
[27] "GSM6068323_20220216_30102684500922-01_Sample10_10.RCC"
[28] "GSM6068324_20220216_30102684500922-01_Sample04_04.RCC"
[29] "GSM6068325_20220217_30102684530922-01_Sample03_03.RCC"
[30] "GSM6068326_20220217_30102684530922-01_Sample06_06.RCC"
[31] "GSM6068327_20220224_30102684540922-01_Sample06_06.RCC"
[32] "GSM6068328_20220204_30102684520922-01_Sample07_07.RCC"
[33] "GSM6068329_20220217_30102684530922-01_Sample05_05.RCC"
[34] "GSM6068330_20220204_30102684520922-01_Sample06_06.RCC"
[35] "GSM6068331_20220204_30102684520922-01_Sample10_10.RCC"
[36] "GSM6068332_20220217_30102684530922-01_Sample10_10.RCC"
[37] "GSM6068333_20220217_30102684530922-01_Sample04_04.RCC"
[38] "GSM6068334_20220224_30102684540922-01_Sample01_01.RCC"
[39] "GSM6068335_20220216_30102684500922-01_Sample02_02.RCC"
[40] "GSM6068336_20220204_30102684520922-01_Sample03_03.RCC"
[41] "GSM6068337_20220216_30102684500922-01_Sample07_07.RCC"
[42] "GSM6068338_20220217_30102684530922-01_Sample08_08.RCC"
[43] "GSM6068339_20210709_30102572870322-01_Sample06_06.RCC"
[44] "GSM6068340_20210709_30102572870322-01_Sample03_03.RCC"
[45] "GSM6068341_20210709_30102572870322-01_Sample04_04.RCC"
[46] "GSM6068342_20210709_30102572870322-01_Sample08_08.RCC"
[47] "GSM6068343_20210707_30102572880322-01_Sample03_03.RCC"
[48] "GSM6068344_20210707_30102572880322-01_Sample01_01.RCC"
[49] "GSM6068345_20210707_30102572880322-01_Sample10_10.RCC"
[50] "GSM6068346_20210707_30102572880322-01_Sample02_02.RCC"
[51] "GSM6068347_20210707_30102572880322-01_Sample06_06.RCC"
[52] "GSM6068348_20210709_30102572870322-01_Sample09_09.RCC"
[53] "GSM6068349_20210707_30102572880322-01_Sample04_04.RCC"
[54] "GSM6068350_20210709_30102572870322-01_Sample11_11.RCC"
[55] "GSM6068351_20220224_30102684540922-01_Sample03_03.RCC"
[56] "GSM6068352_20220224_30102684540922-01_Sample02_02.RCC"
[57] "GSM6068353_20220216_30102684500922-01_Sample09_09.RCC"
[58] "GSM6068354_20220217_30102684530922-01_Sample01_01.RCC"
[59] "GSM6068355_20220204_30102684520922-01_Sample01_01.RCC"
[60] "GSM6068356_20220217_30102684530922-01_Sample02_02.RCC"
[61] "GSM6068357_20220216_30102684500922-01_Sample06_06.RCC"
[62] "GSM6068358_20220216_30102684500922-01_Sample03_03.RCC"
[63] "GSM6068359_20220204_30102684520922-01_Sample09_09.RCC"
[64] "GSM6068360_20220224_30102684540922-01_Sample05_05.RCC"
[65] "GSM6068361_20220204_30102684520922-01_Sample05_05.RCC"
[66] "GSM6068362_20220216_30102684500922-01_Sample01_01.RCC"
[67] "GSM6068363_20220216_30102684500922-01_Sample05_05.RCC"
[68] "GSM6068364_20220216_30102684500922-01_Sample11_11.RCC"
[69] "GSM6068365_20220224_30102684540922-01_Sample07_07.RCC"
[70] "GSM6068366_20220204_30102684520922-01_Sample02_02.RCC"
[71] "GSM6068367_20220204_30102684520922-01_Sample04_04.RCC"
[72] "GSM6068368_20220217_30102684530922-01_Sample07_07.RCC"
[73] "GSM6068369_20220217_30102684530922-01_Sample11_11.RCC"

 [1] "GSM6068308_20210707_30102572880322-01_Sample12_12.RCC"
 [2] "GSM6068309_20210709_30102572870322-01_Sample12_12.RCC"
 [3] "GSM6068310_20210709_30102572870322-01_Sample07_07.RCC"
 [4] "GSM6068311_20210709_30102572870322-01_Sample05_05.RCC"
 [5] "GSM6068312_20210707_30102572880322-01_Sample11_11.RCC"
 [6] "GSM6068313_20210707_30102572880322-01_Sample09_09.RCC"
 [7] "GSM6068314_20210707_30102572880322-01_Sample07_07.RCC"
 [8] "GSM6068315_20210707_30102572880322-01_Sample05_05.RCC"
 [9] "GSM6068316_20210709_30102572870322-01_Sample01_01.RCC"
[10] "GSM6068317_20210709_30102572870322-01_Sample02_02.RCC"
[11] "GSM6068318_20210709_30102572870322-01_Sample10_10.RCC"
[12] "GSM6068319_20210707_30102572880322-01_Sample08_08.RCC"
[13] "GSM6068320_20220216_30102684500922-01_Sample08_08.RCC"
[14] "GSM6068321_20220224_30102684540922-01_Sample04_04.RCC"
[15] "GSM6068322_20220217_30102684530922-01_Sample09_09.RCC"
[16] "GSM6068323_20220216_30102684500922-01_Sample10_10.RCC"
[17] "GSM6068324_20220216_30102684500922-01_Sample04_04.RCC"
[18] "GSM6068325_20220217_30102684530922-01_Sample03_03.RCC"
[19] "GSM6068326_20220217_30102684530922-01_Sample06_06.RCC"
[20] "GSM6068327_20220224_30102684540922-01_Sample06_06.RCC"
[21] "GSM6068328_20220204_30102684520922-01_Sample07_07.RCC"
[22] "GSM6068329_20220217_30102684530922-01_Sample05_05.RCC"
[23] "GSM6068330_20220204_30102684520922-01_Sample06_06.RCC"
[24] "GSM6068331_20220204_30102684520922-01_Sample10_10.RCC"
[25] "GSM6068332_20220217_30102684530922-01_Sample10_10.RCC"
[26] "GSM6068333_20220217_30102684530922-01_Sample04_04.RCC"
[27] "GSM6068334_20220224_30102684540922-01_Sample01_01.RCC"
[28] "GSM6068335_20220216_30102684500922-01_Sample02_02.RCC"
[29] "GSM6068336_20220204_30102684520922-01_Sample03_03.RCC"
[30] "GSM6068337_20220216_30102684500922-01_Sample07_07.RCC"
[31] "GSM6068338_20220217_30102684530922-01_Sample08_08.RCC"
[32] "GSM6068339_20210709_30102572870322-01_Sample06_06.RCC"
[33] "GSM6068340_20210709_30102572870322-01_Sample03_03.RCC"
[34] "GSM6068341_20210709_30102572870322-01_Sample04_04.RCC"
[35] "GSM6068342_20210709_30102572870322-01_Sample08_08.RCC"
[36] "GSM6068343_20210707_30102572880322-01_Sample03_03.RCC"
[37] "GSM6068344_20210707_30102572880322-01_Sample01_01.RCC"
[38] "GSM6068345_20210707_30102572880322-01_Sample10_10.RCC"
[39] "GSM6068346_20210707_30102572880322-01_Sample02_02.RCC"
[40] "GSM6068347_20210707_30102572880322-01_Sample06_06.RCC"
[41] "GSM6068348_20210709_30102572870322-01_Sample09_09.RCC"
[42] "GSM6068349_20210707_30102572880322-01_Sample04_04.RCC"
[43] "GSM6068350_20210709_30102572870322-01_Sample11_11.RCC"
[44] "GSM6068351_20220224_30102684540922-01_Sample03_03.RCC"
[45] "GSM6068352_20220224_30102684540922-01_Sample02_02.RCC"
[46] "GSM6068353_20220216_30102684500922-01_Sample09_09.RCC"
[47] "GSM6068354_20220217_30102684530922-01_Sample01_01.RCC"
[48] "GSM6068355_20220204_30102684520922-01_Sample01_01.RCC"
[49] "GSM6068356_20220217_30102684530922-01_Sample02_02.RCC"
[50] "GSM6068357_20220216_30102684500922-01_Sample06_06.RCC"
[51] "GSM6068358_20220216_30102684500922-01_Sample03_03.RCC"
[52] "GSM6068359_20220204_30102684520922-01_Sample09_09.RCC"
[53] "GSM6068360_20220224_30102684540922-01_Sample05_05.RCC"
[54] "GSM6068361_20220204_30102684520922-01_Sample05_05.RCC"
[55] "GSM6068362_20220216_30102684500922-01_Sample01_01.RCC"
[56] "GSM6068363_20220216_30102684500922-01_Sample05_05.RCC"
[57] "GSM6068364_20220216_30102684500922-01_Sample11_11.RCC"
[58] "GSM6068365_20220224_30102684540922-01_Sample07_07.RCC"
[59] "GSM6068366_20220204_30102684520922-01_Sample02_02.RCC"
[60] "GSM6068367_20220204_30102684520922-01_Sample04_04.RCC"
[61] "GSM6068368_20220217_30102684530922-01_Sample07_07.RCC"
[62] "GSM6068369_20220217_30102684530922-01_Sample11_11.RCC"

In [16]:
norm_counts <- fread("../James_GSE201600//data/counts/nsolver_norm_counts_11.5.24.txt")
colnames(norm_counts)
# replace Surgeny with Surgery (typo on their part)
just_norm_counts = norm_counts[,13:ncol(norm_counts)]
colnames(just_norm_counts)
norm_counts = norm_counts[,1:12]

 [1] "Probe Name"
 [2] "Annotation"
 [3] "Accession #"
 [4] "NS Probe ID"
 [5] "Class Name"
 [6] "Analyte Type"
 [7] "Target Sequence"
 [8] "% Samples above Threshold"
 [9] "Positive Flag"
[10] "Avg Count"
[11] "Min Count"
[12] "Max Count"
[13] "GSM6068308_20210707_30102572880322-01_Sample12_12.RCC"
[14] "GSM6068309_20210709_30102572870322-01_Sample12_12.RCC"
[15] "GSM6068310_20210709_30102572870322-01_Sample07_07.RCC"
[16] "GSM6068311_20210709_30102572870322-01_Sample05_05.RCC"
[17] "GSM6068312_20210707_30102572880322-01_Sample11_11.RCC"
[18] "GSM6068313_20210707_30102572880322-01_Sample09_09.RCC"
[19] "GSM6068314_20210707_30102572880322-01_Sample07_07.RCC"
[20] "GSM6068315_20210707_30102572880322-01_Sample05_05.RCC"
[21] "GSM6068316_20210709_30102572870322-01_Sample01_01.RCC"
[22] "GSM6068317_20210709_30102572870322-01_Sample02_02.RCC"
[23] "GSM6068318_20210709_30102572870322-01_Sample10_10.RCC"
[24] "GSM6068319_20210707_30102572880322-01_Sample08_08.RCC"
[25] "GSM6068320_20220216_30102684500922-01_Sample08_08.RCC"
[26] "GSM6068321_20220224_30102684540922-01_Sample04_04.RCC"
[27] "GSM6068322_20220217_30102684530922-01_Sample09_09.RCC"
[28] "GSM6068323_20220216_30102684500922-01_Sample10_10.RCC"
[29] "GSM6068324_20220216_30102684500922-01_Sample04_04.RCC"
[30] "GSM6068325_20220217_30102684530922-01_Sample03_03.RCC"
[31] "GSM6068326_20220217_30102684530922-01_Sample06_06.RCC"
[32] "GSM6068327_20220224_30102684540922-01_Sample06_06.RCC"
[33] "GSM6068328_20220204_30102684520922-01_Sample07_07.RCC"
[34] "GSM6068329_20220217_30102684530922-01_Sample05_05.RCC"
[35] "GSM6068330_20220204_30102684520922-01_Sample06_06.RCC"
[36] "GSM6068331_20220204_30102684520922-01_Sample10_10.RCC"
[37] "GSM6068332_20220217_30102684530922-01_Sample10_10.RCC"
[38] "GSM6068333_20220217_30102684530922-01_Sample04_04.RCC"
[39] "GSM6068334_20220224_30102684540922-01_Sample01_01.RCC"
[40] "GSM6068335_20220216_30102684500922-01_Sample02_02.RCC"
[41] "GSM6068336_20220204_30102684520922-01_Sample03_03.RCC"
[42] "GSM6068337_20220216_30102684500922-01_Sample07_07.RCC"
[43] "GSM6068338_20220217_30102684530922-01_Sample08_08.RCC"
[44] "GSM6068339_20210709_30102572870322-01_Sample06_06.RCC"
[45] "GSM6068340_20210709_30102572870322-01_Sample03_03.RCC"
[46] "GSM6068341_20210709_30102572870322-01_Sample04_04.RCC"
[47] "GSM6068342_20210709_30102572870322-01_Sample08_08.RCC"
[48] "GSM6068343_20210707_30102572880322-01_Sample03_03.RCC"
[49] "GSM6068344_20210707_30102572880322-01_Sample01_01.RCC"
[50] "GSM6068345_20210707_30102572880322-01_Sample10_10.RCC"
[51] "GSM6068346_20210707_30102572880322-01_Sample02_02.RCC"
[52] "GSM6068347_20210707_30102572880322-01_Sample06_06.RCC"
[53] "GSM6068348_20210709_30102572870322-01_Sample09_09.RCC"
[54] "GSM6068349_20210707_30102572880322-01_Sample04_04.RCC"
[55] "GSM6068350_20210709_30102572870322-01_Sample11_11.RCC"
[56] "GSM6068351_20220224_30102684540922-01_Sample03_03.RCC"
[57] "GSM6068352_20220224_30102684540922-01_Sample02_02.RCC"
[58] "GSM6068353_20220216_30102684500922-01_Sample09_09.RCC"
[59] "GSM6068354_20220217_30102684530922-01_Sample01_01.RCC"
[60] "GSM6068355_20220204_30102684520922-01_Sample01_01.RCC"
[61] "GSM6068356_20220217_30102684530922-01_Sample02_02.RCC"
[62] "GSM6068357_20220216_30102684500922-01_Sample06_06.RCC"
[63] "GSM6068358_20220216_30102684500922-01_Sample03_03.RCC"
[64] "GSM6068359_20220204_30102684520922-01_Sample09_09.RCC"
[65] "GSM6068360_20220224_30102684540922-01_Sample05_05.RCC"
[66] "GSM6068361_20220204_30102684520922-01_Sample05_05.RCC"
[67] "GSM6068362_20220216_30102684500922-01_Sample01_01.RCC"
[68] "GSM6068363_20220216_30102684500922-01_Sample05_05.RCC"
[69] "GSM6068364_20220216_30102684500922-01_Sample11_11.RCC"
[70] "GSM6068365_20220224_30102684540922-01_Sample07_07.RCC"
[71] "GSM6068366_20220204_30102684520922-01_Sample02_02.RCC"
[72] "GSM6068367_20220204_30102684520922-01_Sample04_04.RCC"
[73] "GSM6068368_20220217_30102684530922-01_Sample07_07.RCC"
[74] "GSM6068369_20220217_30102684530922-01_Sample11_11.RCC"

 [1] "GSM6068308_20210707_30102572880322-01_Sample12_12.RCC"
 [2] "GSM6068309_20210709_30102572870322-01_Sample12_12.RCC"
 [3] "GSM6068310_20210709_30102572870322-01_Sample07_07.RCC"
 [4] "GSM6068311_20210709_30102572870322-01_Sample05_05.RCC"
 [5] "GSM6068312_20210707_30102572880322-01_Sample11_11.RCC"
 [6] "GSM6068313_20210707_30102572880322-01_Sample09_09.RCC"
 [7] "GSM6068314_20210707_30102572880322-01_Sample07_07.RCC"
 [8] "GSM6068315_20210707_30102572880322-01_Sample05_05.RCC"
 [9] "GSM6068316_20210709_30102572870322-01_Sample01_01.RCC"
[10] "GSM6068317_20210709_30102572870322-01_Sample02_02.RCC"
[11] "GSM6068318_20210709_30102572870322-01_Sample10_10.RCC"
[12] "GSM6068319_20210707_30102572880322-01_Sample08_08.RCC"
[13] "GSM6068320_20220216_30102684500922-01_Sample08_08.RCC"
[14] "GSM6068321_20220224_30102684540922-01_Sample04_04.RCC"
[15] "GSM6068322_20220217_30102684530922-01_Sample09_09.RCC"
[16] "GSM6068323_20220216_30102684500922-01_Sample10_10.RCC"
[17] "GSM6068324_20220216_30102684500922-01_Sample04_04.RCC"
[18] "GSM6068325_20220217_30102684530922-01_Sample03_03.RCC"
[19] "GSM6068326_20220217_30102684530922-01_Sample06_06.RCC"
[20] "GSM6068327_20220224_30102684540922-01_Sample06_06.RCC"
[21] "GSM6068328_20220204_30102684520922-01_Sample07_07.RCC"
[22] "GSM6068329_20220217_30102684530922-01_Sample05_05.RCC"
[23] "GSM6068330_20220204_30102684520922-01_Sample06_06.RCC"
[24] "GSM6068331_20220204_30102684520922-01_Sample10_10.RCC"
[25] "GSM6068332_20220217_30102684530922-01_Sample10_10.RCC"
[26] "GSM6068333_20220217_30102684530922-01_Sample04_04.RCC"
[27] "GSM6068334_20220224_30102684540922-01_Sample01_01.RCC"
[28] "GSM6068335_20220216_30102684500922-01_Sample02_02.RCC"
[29] "GSM6068336_20220204_30102684520922-01_Sample03_03.RCC"
[30] "GSM6068337_20220216_30102684500922-01_Sample07_07.RCC"
[31] "GSM6068338_20220217_30102684530922-01_Sample08_08.RCC"
[32] "GSM6068339_20210709_30102572870322-01_Sample06_06.RCC"
[33] "GSM6068340_20210709_30102572870322-01_Sample03_03.RCC"
[34] "GSM6068341_20210709_30102572870322-01_Sample04_04.RCC"
[35] "GSM6068342_20210709_30102572870322-01_Sample08_08.RCC"
[36] "GSM6068343_20210707_30102572880322-01_Sample03_03.RCC"
[37] "GSM6068344_20210707_30102572880322-01_Sample01_01.RCC"
[38] "GSM6068345_20210707_30102572880322-01_Sample10_10.RCC"
[39] "GSM6068346_20210707_30102572880322-01_Sample02_02.RCC"
[40] "GSM6068347_20210707_30102572880322-01_Sample06_06.RCC"
[41] "GSM6068348_20210709_30102572870322-01_Sample09_09.RCC"
[42] "GSM6068349_20210707_30102572880322-01_Sample04_04.RCC"
[43] "GSM6068350_20210709_30102572870322-01_Sample11_11.RCC"
[44] "GSM6068351_20220224_30102684540922-01_Sample03_03.RCC"
[45] "GSM6068352_20220224_30102684540922-01_Sample02_02.RCC"
[46] "GSM6068353_20220216_30102684500922-01_Sample09_09.RCC"
[47] "GSM6068354_20220217_30102684530922-01_Sample01_01.RCC"
[48] "GSM6068355_20220204_30102684520922-01_Sample01_01.RCC"
[49] "GSM6068356_20220217_30102684530922-01_Sample02_02.RCC"
[50] "GSM6068357_20220216_30102684500922-01_Sample06_06.RCC"
[51] "GSM6068358_20220216_30102684500922-01_Sample03_03.RCC"
[52] "GSM6068359_20220204_30102684520922-01_Sample09_09.RCC"
[53] "GSM6068360_20220224_30102684540922-01_Sample05_05.RCC"
[54] "GSM6068361_20220204_30102684520922-01_Sample05_05.RCC"
[55] "GSM6068362_20220216_30102684500922-01_Sample01_01.RCC"
[56] "GSM6068363_20220216_30102684500922-01_Sample05_05.RCC"
[57] "GSM6068364_20220216_30102684500922-01_Sample11_11.RCC"
[58] "GSM6068365_20220224_30102684540922-01_Sample07_07.RCC"
[59] "GSM6068366_20220204_30102684520922-01_Sample02_02.RCC"
[60] "GSM6068367_20220204_30102684520922-01_Sample04_04.RCC"
[61] "GSM6068368_20220217_30102684530922-01_Sample07_07.RCC"
[62] "GSM6068369_20220217_30102684530922-01_Sample11_11.RCC"

In [17]:
# get the vector for renaming (like a dictionary)
rename_vector = metadata$Name
# names are what is currrently in counts
names(rename_vector) = metadata$count_name

In [18]:
# Rename the columns in df1 that match the key-value pairs in df2
colnames(just_norm_counts)[colnames(just_norm_counts) %in% names(rename_vector)] <- rename_vector[colnames(just_norm_counts)[colnames(just_norm_counts) %in% names(rename_vector)]]
colnames(just_norm_counts)

colnames(just_raw_counts)[colnames(just_raw_counts) %in% names(rename_vector)] <- rename_vector[colnames(just_raw_counts)[colnames(just_raw_counts) %in% names(rename_vector)]]
colnames(just_raw_counts)

 [1] "P1_Post"  "P2_Post"  "P3_Post"  "P4_Post"  "P5_Post"  "P6_Post"
 [7] "P7_Post"  "P8_Post"  "P9_Post"  "P10_Post" "P11_Post" "P12_Post"
[13] "P13_Post" "P14_Post" "P15_Post" "P16_Post" "P17_Post" "P18_Post"
[19] "P19_Post" "P20_Post" "P21_Post" "P22_Post" "P23_Post" "P24_Post"
[25] "P25_Post" "P26_Post" "P27_Post" "P28_Post" "P29_Post" "P30_Post"
[31] "P31_Post" "P1_Pre"   "P2_Pre"   "P3_Pre"   "P4_Pre"   "P5_Pre"
[37] "P6_Pre"   "P7_Pre"   "P8_Pre"   "P9_Pre"   "P10_Pre"  "P11_Pre"
[43] "P12_Pre"  "P13_Pre"  "P14_Pre"  "P15_Pre"  "P16_Pre"  "P17_Pre"
[49] "P18_Pre"  "P19_Pre"  "P20_Pre"  "P21_Pre"  "P22_Pre"  "P23_Pre"
[55] "P24_Pre"  "P25_Pre"  "P26_Pre"  "P27_Pre"  "P28_Pre"  "P29_Pre"
[61] "P30_Pre"  "P31_Pre"

 [1] "P1_Post"  "P2_Post"  "P3_Post"  "P4_Post"  "P5_Post"  "P6_Post"
 [7] "P7_Post"  "P8_Post"  "P9_Post"  "P10_Post" "P11_Post" "P12_Post"
[13] "P13_Post" "P14_Post" "P15_Post" "P16_Post" "P17_Post" "P18_Post"
[19] "P19_Post" "P20_Post" "P21_Post" "P22_Post" "P23_Post" "P24_Post"
[25] "P25_Post" "P26_Post" "P27_Post" "P28_Post" "P29_Post" "P30_Post"
[31] "P31_Post" "P1_Pre"   "P2_Pre"   "P3_Pre"   "P4_Pre"   "P5_Pre"
[37] "P6_Pre"   "P7_Pre"   "P8_Pre"   "P9_Pre"   "P10_Pre"  "P11_Pre"
[43] "P12_Pre"  "P13_Pre"  "P14_Pre"  "P15_Pre"  "P16_Pre"  "P17_Pre"
[49] "P18_Pre"  "P19_Pre"  "P20_Pre"  "P21_Pre"  "P22_Pre"  "P23_Pre"
[55] "P24_Pre"  "P25_Pre"  "P26_Pre"  "P27_Pre"  "P28_Pre"  "P29_Pre"
[61] "P30_Pre"  "P31_Pre"

In [19]:
# recombine and save
norm_counts <- cbind(norm_counts, just_norm_counts)
raw_counts <- cbind(raw_counts, just_raw_counts)
colnames(norm_counts)
colnames(raw_counts)

 [1] "Probe Name"                "Annotation"
 [3] "Accession #"               "NS Probe ID"
 [5] "Class Name"                "Analyte Type"
 [7] "Target Sequence"           "% Samples above Threshold"
 [9] "Positive Flag"             "Avg Count"
[11] "Min Count"                 "Max Count"
[13] "P1_Post"                   "P2_Post"
[15] "P3_Post"                   "P4_Post"
[17] "P5_Post"                   "P6_Post"
[19] "P7_Post"                   "P8_Post"
[21] "P9_Post"                   "P10_Post"
[23] "P11_Post"                  "P12_Post"
[25] "P13_Post"                  "P14_Post"
[27] "P15_Post"                  "P16_Post"
[29] "P17_Post"                  "P18_Post"
[31] "P19_Post"                  "P20_Post"
[33] "P21_Post"                  "P22_Post"
[35] "P23_Post"                  "P24_Post"
[37] "P25_Post"                  "P26_Post"
[39] "P27_Post"                  "P28_Post"
[41] "P29_Post"                  "P30_Post"
[43] "P31_Post"                  "P1_Pre"
[45] "P2_Pre"                    "P3_Pre"
[47] "P4_Pre"                    "P5_Pre"
[49] "P6_Pre"                    "P7_Pre"
[51] "P8_Pre"                    "P9_Pre"
[53] "P10_Pre"                   "P11_Pre"
[55] "P12_Pre"                   "P13_Pre"
[57] "P14_Pre"                   "P15_Pre"
[59] "P16_Pre"                   "P17_Pre"
[61] "P18_Pre"                   "P19_Pre"
[63] "P20_Pre"                   "P21_Pre"
[65] "P22_Pre"                   "P23_Pre"
[67] "P24_Pre"                   "P25_Pre"
[69] "P26_Pre"                   "P27_Pre"
[71] "P28_Pre"                   "P29_Pre"
[73] "P30_Pre"                   "P31_Pre"

 [1] "Probe Name"                "Annotation"
 [3] "Accession #"               "NS Probe ID"
 [5] "Class Name"                "Analyte Type"
 [7] "% Samples above Threshold" "Positive Flag"
 [9] "Avg Count"                 "Min Count"
[11] "Max Count"                 "P1_Post"
[13] "P2_Post"                   "P3_Post"
[15] "P4_Post"                   "P5_Post"
[17] "P6_Post"                   "P7_Post"
[19] "P8_Post"                   "P9_Post"
[21] "P10_Post"                  "P11_Post"
[23] "P12_Post"                  "P13_Post"
[25] "P14_Post"                  "P15_Post"
[27] "P16_Post"                  "P17_Post"
[29] "P18_Post"                  "P19_Post"
[31] "P20_Post"                  "P21_Post"
[33] "P22_Post"                  "P23_Post"
[35] "P24_Post"                  "P25_Post"
[37] "P26_Post"                  "P27_Post"
[39] "P28_Post"                  "P29_Post"
[41] "P30_Post"                  "P31_Post"
[43] "P1_Pre"                    "P2_Pre"
[45] "P3_Pre"                    "P4_Pre"
[47] "P5_Pre"                    "P6_Pre"
[49] "P7_Pre"                    "P8_Pre"
[51] "P9_Pre"                    "P10_Pre"
[53] "P11_Pre"                   "P12_Pre"
[55] "P13_Pre"                   "P14_Pre"
[57] "P15_Pre"                   "P16_Pre"
[59] "P17_Pre"                   "P18_Pre"
[61] "P19_Pre"                   "P20_Pre"
[63] "P21_Pre"                   "P22_Pre"
[65] "P23_Pre"                   "P24_Pre"
[67] "P25_Pre"                   "P26_Pre"
[69] "P27_Pre"                   "P28_Pre"
[71] "P29_Pre"                   "P30_Pre"
[73] "P31_Pre"

In [20]:
norm_counts[1:2,]
raw_counts[1:2,]

  Probe Name Annotation Accession # NS Probe ID Class Name Analyte Type
1 A2M        NA         NM_000014.4 NA          Endogenous mRNA
2 ACVR1C     NA         NM_145259.2 NA          Endogenous mRNA
  Target Sequence % Samples above Threshold Positive Flag Avg Count ... P22_Pre
1 NA              100.00                    FALSE         1633.90   ... 1165.26
2 NA               83.87                    FALSE           38.12   ...   14.24
  P23_Pre P24_Pre P25_Pre P26_Pre P27_Pre P28_Pre P29_Pre P30_Pre P31_Pre
1 1894.73 495.69  3298.90 974.21  1711.50 1015.26 804.44  2663.09 2511.01
2  105.58  41.11    11.88  31.43    11.62   27.13  44.11    77.75   26.95

  Probe Name Annotation Accession # NS Probe ID Class Name Analyte Type
1 A2M        NA         NM_000014.4 NA          Endogenous mRNA
2 ACVR1C     NA         NM_145259.2 NA          Endogenous mRNA
  % Samples above Threshold Positive Flag Avg Count Min Count ... P22_Pre
1 100.0                     FALSE         1444.65   109       ... 1146
2  87.1                     FALSE           30.85     8       ...   14
  P23_Pre P24_Pre P25_Pre P26_Pre P27_Pre P28_Pre P29_Pre P30_Pre P31_Pre
1 1974    205     1485    899     784     898     620     1096    2143
2  110     17        9     29       8      24      34       32      23

In [19]:
write.table(norm_counts, "../James_GSE201600//data/counts/nsolver_norm_counts_11.5.24_clean.txt", sep="\t", quote=FALSE, row.names=FALSE)
write.table(raw_counts, "../James_GSE201600//data/counts/nsolver_raw_counts_11.5.24_clean.txt", sep="\t", quote=FALSE, row.names=FALSE)

## 3. Manso

In [21]:
# get the metadata to split into Pre and Post
GSE="GSE181597"
gset <- getGEO(GSE, GSEMatrix =TRUE, getGPL=FALSE)
gset <- gset[[1]]

Found 1 file(s)

GSE181597_series_matrix.txt.gz

In [22]:

phenodf <- pData(gset)
colnames(phenodf)
phenodf[1:2,]

table(phenodf[["description"]])
table(phenodf[["data_processing"]])
table(phenodf[["response to nact:ch1"]])
table(phenodf[["crs score:ch1"]])
table(phenodf[["sample type:ch1"]])
table(phenodf[["tissue:ch1"]])


# get the metadata
metadata = phenodf[,c("geo_accession", "source_name_ch1", "description", "title", 'response to nact:ch1', 
                      "crs score:ch1", "sample type:ch1", "tissue:ch1")]
metadata[1:2,]

 [1] "title"                   "geo_accession"
 [3] "status"                  "submission_date"
 [5] "last_update_date"        "type"
 [7] "channel_count"           "source_name_ch1"
 [9] "organism_ch1"            "characteristics_ch1"
[11] "characteristics_ch1.1"   "characteristics_ch1.2"
[13] "characteristics_ch1.3"   "treatment_protocol_ch1"
[15] "molecule_ch1"            "extract_protocol_ch1"
[17] "label_ch1"               "label_protocol_ch1"
[19] "taxid_ch1"               "hyb_protocol"
[21] "scan_protocol"           "description"
[23] "data_processing"         "platform_id"
[25] "contact_name"            "contact_email"
[27] "contact_phone"           "contact_laboratory"
[29] "contact_institute"       "contact_address"
[31] "contact_city"            "contact_state"
[33] "contact_zip/postal_code" "contact_country"
[35] "supplementary_file"      "data_row_count"
[37] "crs score:ch1"           "response to nact:ch1"
[39] "sample type:ch1"         "tissue:ch1"

           title                geo_accession status
GSM5507801 Biopsy_before_NACT_1 GSM5507801    Public on Jan 27 2022
GSM5507802 Biopsy_before_NACT_2 GSM5507802    Public on Jan 27 2022
           submission_date last_update_date type channel_count
GSM5507801 Aug 06 2021     Jan 27 2022      RNA  1
GSM5507802 Aug 06 2021     Jan 27 2022      RNA  1
           source_name_ch1
GSM5507801 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_1
GSM5507802 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_2
           organism_ch1 characteristics_ch1               ... contact_city
GSM5507801 Homo sapiens tissue: Epithelial Ovarian Cancer ... Madrid
GSM5507802 Homo sapiens tissue: Epithelial Ovarian Cancer ... Madrid
           contact_state contact_zip/postal_code contact_country
GSM5507801 Madrid        28040                   Spain
GSM5507802 Madrid        28040                   Spain
           supplementary_file
GSM5507801 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5507nnn/GSM5507801/suppl/GSM5507801_Biopsy_before_NACT_1.RCC.gz
GSM5507802 ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5507nnn/GSM5507802/suppl/GSM5507802_Biopsy_before_NACT_2.RCC.gz
           data_row_count crs score:ch1 response to nact:ch1 sample type:ch1
GSM5507801 750            3             Responder            Biopsy sample
GSM5507802 750            2             Non-responder        Biopsy sample
           tissue:ch1
GSM5507801 Epithelial Ovarian Cancer
GSM5507802 Epithelial Ovarian Cancer

                               Paired with surgery sample 1
                           27                             1
Paired with surgery sample 10 Paired with surgery sample 11
                            1                             1
Paired with surgery sample 12 Paired with surgery sample 13
                            1                             1
Paired with surgery sample 14 Paired with surgery sample 15
                            1                             1
Paired with surgery sample 16 Paired with surgery sample 17
                            1                             1
Paired with surgery sample 18 Paired with surgery sample 19
                            1                             1
 Paired with surgery sample 3  Paired with surgery sample 4
                            1                             1
 Paired with surgery sample 5  Paired with surgery sample 6
                            1                             1
 Paired with surgery sample 8  Paired with surgery sample 9
                            1                             1

nanoString data were analyzed and normalized in nSolver software, correcting for the expression of technical controls and 30 housekeeping genes included in the panel.
                                                                                                                                                                    44

Non-responder     Responder
           27            17

 1  2  3
 7 15 22

 Biopsy sample Surgery sample
            25             19

Epithelial Ovarian Cancer
                       44

           geo_accession
GSM5507801 GSM5507801
GSM5507802 GSM5507802
           source_name_ch1
GSM5507801 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_1
GSM5507802 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_2
           description                  title
GSM5507801 Paired with surgery sample 1 Biopsy_before_NACT_1
GSM5507802                              Biopsy_before_NACT_2
           response to nact:ch1 crs score:ch1 sample type:ch1
GSM5507801 Responder            3             Biopsy sample
GSM5507802 Non-responder        2             Biopsy sample
           tissue:ch1
GSM5507801 Epithelial Ovarian Cancer
GSM5507802 Epithelial Ovarian Cancer

In [23]:
unique(metadata$title)

 [1] "Biopsy_before_NACT_1"  "Biopsy_before_NACT_2"  "Biopsy_before_NACT_3"
 [4] "Biopsy_before_NACT_4"  "Biopsy_before_NACT_5"  "Biopsy_before_NACT_6"
 [7] "Biopsy_before_NACT_7"  "Biopsy_before_NACT_8"  "Biopsy_before_NACT_9"
[10] "Biopsy_before_NACT_10" "Biopsy_before_NACT_11" "Biopsy_before_NACT_12"
[13] "Biopsy_before_NACT_13" "Biopsy_before_NACT_14" "Biopsy_before_NACT_15"
[16] "Biopsy_before_NACT_16" "Biopsy_before_NACT_17" "Biopsy_before_NACT_18"
[19] "Biopsy_before_NACT_19" "Biopsy_before_NACT_20" "Biopsy_before_NACT_21"
[22] "Biopsy_before_NACT_22" "Biopsy_before_NACT_23" "Biopsy_before_NACT_24"
[25] "Biopsy_before_NACT_25" "Surgery_after_NACT_1"  "Surgery_after_NACT_2"
[28] "Surgery_after_NACT_3"  "Surgery_after_NACT_4"  "Surgery_after_NACT_5"
[31] "Surgery_after_NACT_6"  "Surgery_after_NACT_7"  "Surgery_after_NACT_8"
[34] "Surgery_after_NACT_9"  "Surgery_after_NACT_10" "Surgery_after_NACT_11"
[37] "Surgery_after_NACT_12" "Surgery_after_NACT_13" "Surgery_after_NACT_14"
[40] "Surgery_after_NACT_15" "Surgery_after_NACT_16" "Surgery_after_NACT_17"
[43] "Surgery_after_NACT_18" "Surgery_after_NACT_19"

In [24]:
colnames(metadata)

[1] "geo_accession"        "source_name_ch1"      "description"
[4] "title"                "response to nact:ch1" "crs score:ch1"
[7] "sample type:ch1"      "tissue:ch1"

### 3B. Synthesize with Grace Metadata

In [25]:
grace_meta[1:2,]
manso_grace_meta = as.data.frame(grace_meta[grace_meta$Source == "PMID:35087175",])
manso_grace_meta[1:3,]
# 32928797 - Bitler
# 35087175 - Manso

  PRE SAMPLE ID
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
  POST SAMPLE ID                             Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55   8  1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
  PFS_high Chemo_status PFS_high_32928797 OS Death
1 0        1            0                 44 1
2 1        2            1                 51 0

  PRE SAMPLE ID                       POST SAMPLE ID
1 GSM5507801_Biopsy_before_NACT_1.RCC GSM5507826_Surgeny_after_NACT_1.RCC
2 GSM5507804_Biopsy_before_NACT_4.RCC GSM5507828_Surgeny_after_NACT_3.RCC
3 GSM5507806_Biopsy_before_NACT_6.RCC GSM5507830_Surgeny_after_NACT_5.RCC
  Source        Age PFS Recurrence PFS_high Chemo_status PFS_high_32928797 OS
1 PMID:35087175 NA  27  1          1        2            NA                NA
2 PMID:35087175 NA  91  0          1        2            NA                NA
3 PMID:35087175 NA  18  1          1        2            NA                NA
  Death
1 NA
2 NA
3 NA

In [26]:
metadata[1:2,]
metadata$name <- paste0(metadata$geo_accession, "_", metadata$title, ".RCC")
length(metadata$name)

           geo_accession
GSM5507801 GSM5507801
GSM5507802 GSM5507802
           source_name_ch1
GSM5507801 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_1
GSM5507802 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_2
           description                  title
GSM5507801 Paired with surgery sample 1 Biopsy_before_NACT_1
GSM5507802                              Biopsy_before_NACT_2
           response to nact:ch1 crs score:ch1 sample type:ch1
GSM5507801 Responder            3             Biopsy sample
GSM5507802 Non-responder        2             Biopsy sample
           tissue:ch1
GSM5507801 Epithelial Ovarian Cancer
GSM5507802 Epithelial Ovarian Cancer

[1] 44

In [27]:
# get proper pairings (original pairings based on numbers alone are incorrect)

# proper pairings: The NACT does nOT refer to actual patient pairings so I need to fix that
## proper pairings are in the descriptions
pairings = c("GSM5507801"="P1", "GSM5507826"="P1",
             "GSM5507804"="P2", "GSM5507828"="P2", 
             "GSM5507806"="P3", "GSM5507830"="P3", 
             "GSM5507807"="P4", "GSM5507831"="P4", 
             "GSM5507808"="P5", "GSM5507833"="P5", 
             "GSM5507809"="P6", "GSM5507834"="P6", 
             "GSM5507810"="P7", "GSM5507835"="P7", 
             "GSM5507811"="P8", "GSM5507836"="P8", 
             "GSM5507812"="P9", "GSM5507837"="P9", 
             "GSM5507815"="P10", "GSM5507838"="P10", 
             "GSM5507818"="P11", "GSM5507839"="P11", 
             "GSM5507820"="P12", "GSM5507840"="P12", 
             "GSM5507821"="P13", "GSM5507841"="P13", 
             "GSM5507823"="P14", "GSM5507842"="P14", 
             "GSM5507824"="P15", "GSM5507843"="P15", 
             "GSM5507825"="P16", "GSM5507844"="P16", 
             "GSM5507805"="P17", "GSM5507829"="P17")
length(pairings)


True_Patient_list = c()
for (index in seq(1, nrow(metadata))) {
    gsm = metadata$geo_accession[index]
    if (gsm %in% names(pairings)) {
        True_Patient_list = c(True_Patient_list, pairings[[gsm]])
    } else {
        True_Patient_list = c(True_Patient_list, "NA")
    }
    
    }
metadata$True_Patient <- True_Patient_list       

# now replace the columns with easy names
# get easy names in the metadata
split <- str_split_fixed(metadata$title, "_", 4)
metadata$Name <- paste0(metadata$True_Patient, "_", split[,2])
metadata[1:2,]


# NA values are NOT paired samples
table(metadata$True_Patient)

metadata <- metadata[metadata$True_Patient != "NA",]
metadata$Treatment_status <- "NA"
unique(metadata["sample type:ch1"])
metadata[metadata["sample type:ch1"] == "Biopsy sample",]$Treatment_status <- "Pre"
metadata[metadata["sample type:ch1"] == "Surgery sample",]$Treatment_status <- "Post"
metadata$Name <- paste0(metadata$True_Patient, "_", metadata$Treatment_status)

[1] 34

           geo_accession
GSM5507801 GSM5507801
GSM5507802 GSM5507802
           source_name_ch1
GSM5507801 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_1
GSM5507802 Biopsy sample from Epithelial Ovarian Carcinoma before carboplatin/paclitaxel-based NACT_2
           description                  title
GSM5507801 Paired with surgery sample 1 Biopsy_before_NACT_1
GSM5507802                              Biopsy_before_NACT_2
           response to nact:ch1 crs score:ch1 sample type:ch1
GSM5507801 Responder            3             Biopsy sample
GSM5507802 Non-responder        2             Biopsy sample
           tissue:ch1                name
GSM5507801 Epithelial Ovarian Cancer GSM5507801_Biopsy_before_NACT_1.RCC
GSM5507802 Epithelial Ovarian Cancer GSM5507802_Biopsy_before_NACT_2.RCC
           True_Patient Name
GSM5507801 P1           P1_before
GSM5507802 NA           NA_before

 NA  P1 P10 P11 P12 P13 P14 P15 P16 P17  P2  P3  P4  P5  P6  P7  P8  P9
 10   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2

           sample type:ch1
GSM5507801 Biopsy sample
GSM5507826 Surgery sample

In [28]:
# get into format comparable to grae metadata
metadat_wide_manso <- metadata %>%
  pivot_wider(
    id_cols = c(True_Patient, "response to nact:ch1", "crs score:ch1"),
    names_from = Treatment_status,
    values_from = name,
    names_prefix = "",
    names_glue = "{Treatment_status}_count_name"
  )
metadat_wide_manso[1:4,]

  True_Patient response to nact:ch1 crs score:ch1
1 P1           Responder            3
2 P2           Responder            3
3 P17          Responder            3
4 P3           Non-responder        2
  Pre_count_name                      Post_count_name
1 GSM5507801_Biopsy_before_NACT_1.RCC GSM5507826_Surgery_after_NACT_1.RCC
2 GSM5507804_Biopsy_before_NACT_4.RCC GSM5507828_Surgery_after_NACT_3.RCC
3 GSM5507805_Biopsy_before_NACT_5.RCC GSM5507829_Surgery_after_NACT_4.RCC
4 GSM5507806_Biopsy_before_NACT_6.RCC GSM5507830_Surgery_after_NACT_5.RCC

In [29]:
#metadata[1:2,]
#grace_meta[1:2,]

matched_grace_meta <- grace_meta[grace_meta[["PRE SAMPLE ID"]] %in% metadat_wide_manso$Pre_count_name,]
#matched_grace_meta[1:4,]
dim(matched_grace_meta)
#metadata[1:2,]

metadat_wide_manso <- merge(metadat_wide_manso, matched_grace_meta[,c("PRE SAMPLE ID", "Source", "Age", "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_32928797", "OS", "Death")], by.x=c("Pre_count_name"), by.y=c("PRE SAMPLE ID"))

metadat_wide_manso[1:3,]

[1] 17 11

  Pre_count_name                      True_Patient response to nact:ch1
1 GSM5507801_Biopsy_before_NACT_1.RCC P1           Responder
2 GSM5507804_Biopsy_before_NACT_4.RCC P2           Responder
3 GSM5507805_Biopsy_before_NACT_5.RCC P17          Responder
  crs score:ch1 Post_count_name                     Source        Age PFS
1 3             GSM5507826_Surgery_after_NACT_1.RCC PMID:35087175 NA  27
2 3             GSM5507828_Surgery_after_NACT_3.RCC PMID:35087175 NA  91
3 3             GSM5507829_Surgery_after_NACT_4.RCC PMID:35087175 NA  54
  Recurrence PFS_high Chemo_status PFS_high_32928797 OS Death
1 1          1        2            NA                NA NA
2 0          1        2            NA                NA NA
3 0          1        2            NA                NA NA

In [30]:
metadat_wide_manso

   Pre_count_name                       True_Patient response to nact:ch1
1  GSM5507801_Biopsy_before_NACT_1.RCC  P1           Responder
2  GSM5507804_Biopsy_before_NACT_4.RCC  P2           Responder
3  GSM5507805_Biopsy_before_NACT_5.RCC  P17          Responder
4  GSM5507806_Biopsy_before_NACT_6.RCC  P3           Non-responder
5  GSM5507807_Biopsy_before_NACT_7.RCC  P4           Non-responder
6  GSM5507808_Biopsy_before_NACT_8.RCC  P5           Non-responder
7  GSM5507809_Biopsy_before_NACT_9.RCC  P6           Responder
8  GSM5507810_Biopsy_before_NACT_10.RCC P7           Non-responder
9  GSM5507811_Biopsy_before_NACT_11.RCC P8           Non-responder
10 GSM5507812_Biopsy_before_NACT_12.RCC P9           Non-responder
11 GSM5507815_Biopsy_before_NACT_15.RCC P10          Non-responder
12 GSM5507818_Biopsy_before_NACT_18.RCC P11          Responder
13 GSM5507820_Biopsy_before_NACT_20.RCC P12          Non-responder
14 GSM5507821_Biopsy_before_NACT_21.RCC P13          Responder
15 GSM5507823_Biopsy_before_NACT_23.RCC P14          Non-responder
16 GSM5507824_Biopsy_before_NACT_24.RCC P15          Non-responder
17 GSM5507825_Biopsy_before_NACT_25.RCC P16          Non-responder
   crs score:ch1 Post_count_name                      Source        Age PFS
1  3             GSM5507826_Surgery_after_NACT_1.RCC  PMID:35087175 NA   27
2  3             GSM5507828_Surgery_after_NACT_3.RCC  PMID:35087175 NA   91
3  3             GSM5507829_Surgery_after_NACT_4.RCC  PMID:35087175 NA   54
4  2             GSM5507830_Surgery_after_NACT_5.RCC  PMID:35087175 NA   18
5  2             GSM5507831_Surgery_after_NACT_6.RCC  PMID:35087175 NA    7
6  2             GSM5507833_Surgery_after_NACT_8.RCC  PMID:35087175 NA   50
7  3             GSM5507834_Surgery_after_NACT_9.RCC  PMID:35087175 NA  103
8  2             GSM5507835_Surgery_after_NACT_10.RCC PMID:35087175 NA   15
9  1             GSM5507836_Surgery_after_NACT_11.RCC PMID:35087175 NA    8
10 2             GSM5507837_Surgery_after_NACT_12.RCC PMID:35087175 NA  109
11 2             NA                                   PMID:35087175 NA    5
12 3             GSM5507839_Surgery_after_NACT_14.RCC PMID:35087175 NA  132
13 1             GSM5507840_Surgery_after_NACT_15.RCC PMID:35087175 NA    1
14 3             GSM5507841_Surgery_after_NACT_16.RCC PMID:35087175 NA   71
15 2             GSM5507842_Surgery_after_NACT_17.RCC PMID:35087175 NA   17
16 1             GSM5507843_Surgery_after_NACT_18.RCC PMID:35087175 NA   11
17 3             GSM5507844_Surgery_after_NACT_19.RCC PMID:35087175 NA   14
   Recurrence PFS_high Chemo_status PFS_high_32928797 OS Death
1  1          1        2            NA                NA NA
2  0          1        2            NA                NA NA
3  0          1        2            NA                NA NA
4  1          1        2            NA                NA NA
5  1          0        1            NA                NA NA
6  1          1        2            NA                NA NA
7  0          1        2            NA                NA NA
8  1          1        2            NA                NA NA
9  1          0        1            NA                NA NA
10 0          1        2            NA                NA NA
11 1          0        0            NA                NA NA
12 0          1        2            NA                NA NA
13 1          0        0            NA                NA NA
14 1          1        2            NA                NA NA
15 1          1        2            NA                NA NA
16 1          1        1            NA                NA NA
17 1          1        2            NA                NA NA

### Synthesize with counts

In [31]:
raw_counts <- fread("../Manso_GSE181597/data/counts/nSolver_rawcounts_09.23.24.txt")
colnames(raw_counts)
colnames(raw_counts) <- gsub("Surgeny", "Surgery", colnames(raw_counts))
# replace Surgeny with Surgery (typo on their part)

 [1] "Probe Name"
 [2] "Annotation"
 [3] "Accession #"
 [4] "NS Probe ID"
 [5] "Class Name"
 [6] "Analyte Type"
 [7] "% Samples above Threshold"
 [8] "Avg Count"
 [9] "Min Count"
[10] "Max Count"
[11] "GSM5507801_Biopsy_before_NACT_1.RCC"
[12] "GSM5507802_Biopsy_before_NACT_2.RCC"
[13] "GSM5507803_Biopsy_before_NACT_3.RCC"
[14] "GSM5507804_Biopsy_before_NACT_4.RCC"
[15] "GSM5507805_Biopsy_before_NACT_5.RCC"
[16] "GSM5507806_Biopsy_before_NACT_6.RCC"
[17] "GSM5507807_Biopsy_before_NACT_7.RCC"
[18] "GSM5507808_Biopsy_before_NACT_8.RCC"
[19] "GSM5507809_Biopsy_before_NACT_9.RCC"
[20] "GSM5507810_Biopsy_before_NACT_10.RCC"
[21] "GSM5507811_Biopsy_before_NACT_11.RCC"
[22] "GSM5507812_Biopsy_before_NACT_12.RCC"
[23] "GSM5507813_Biopsy_before_NACT_13.RCC"
[24] "GSM5507814_Biopsy_before_NACT_14.RCC"
[25] "GSM5507815_Biopsy_before_NACT_15.RCC"
[26] "GSM5507816_Biopsy_before_NACT_16.RCC"
[27] "GSM5507817_Biopsy_before_NACT_17.RCC"
[28] "GSM5507818_Biopsy_before_NACT_18.RCC"
[29] "GSM5507819_Biopsy_before_NACT_19.RCC"
[30] "GSM5507820_Biopsy_before_NACT_20.RCC"
[31] "GSM5507821_Biopsy_before_NACT_21.RCC"
[32] "GSM5507822_Biopsy_before_NACT_22.RCC"
[33] "GSM5507823_Biopsy_before_NACT_23.RCC"
[34] "GSM5507824_Biopsy_before_NACT_24.RCC"
[35] "GSM5507825_Biopsy_before_NACT_25.RCC"
[36] "GSM5507826_Surgeny_after_NACT_1.RCC"
[37] "GSM5507827_Surgeny_after_NACT_2.RCC"
[38] "GSM5507828_Surgeny_after_NACT_3.RCC"
[39] "GSM5507829_Surgeny_after_NACT_4.RCC"
[40] "GSM5507830_Surgeny_after_NACT_5.RCC"
[41] "GSM5507831_Surgeny_after_NACT_6.RCC"
[42] "GSM5507832_Surgeny_after_NACT_7.RCC"
[43] "GSM5507833_Surgeny_after_NACT_8.RCC"
[44] "GSM5507834_Surgeny_after_NACT_9.RCC"
[45] "GSM5507835_Surgeny_after_NACT_10.RCC"
[46] "GSM5507836_Surgeny_after_NACT_11.RCC"
[47] "GSM5507837_Surgeny_after_NACT_12.RCC"
[48] "GSM5507838_Surgeny_after_NACT_13.RCC"
[49] "GSM5507839_Surgeny_after_NACT_14.RCC"
[50] "GSM5507840_Surgeny_after_NACT_15.RCC"
[51] "GSM5507841_Surgeny_after_NACT_16.RCC"
[52] "GSM5507842_Surgeny_after_NACT_17.RCC"
[53] "GSM5507843_Surgeny_after_NACT_18.RCC"
[54] "GSM5507844_Surgeny_after_NACT_19.RCC"

In [32]:
counts <- fread("../Manso_GSE181597/data/counts/nSolver_normcounts_5.30.25.txt")
colnames(counts)
colnames(counts) <- gsub("Surgeny", "Surgery", colnames(counts))
# replace Surgeny with Surgery (typo on their part)

 [1] "Probe Name"
 [2] "Annotation"
 [3] "Accession #"
 [4] "NS Probe ID"
 [5] "Class Name"
 [6] "Analyte Type"
 [7] "Target Sequence"
 [8] "% Samples above Threshold"
 [9] "Positive Flag"
[10] "Avg Count"
[11] "Min Count"
[12] "Max Count"
[13] "GSM5507801_Biopsy_before_NACT_1.RCC"
[14] "GSM5507804_Biopsy_before_NACT_4.RCC"
[15] "GSM5507805_Biopsy_before_NACT_5.RCC"
[16] "GSM5507806_Biopsy_before_NACT_6.RCC"
[17] "GSM5507807_Biopsy_before_NACT_7.RCC"
[18] "GSM5507808_Biopsy_before_NACT_8.RCC"
[19] "GSM5507809_Biopsy_before_NACT_9.RCC"
[20] "GSM5507810_Biopsy_before_NACT_10.RCC"
[21] "GSM5507811_Biopsy_before_NACT_11.RCC"
[22] "GSM5507812_Biopsy_before_NACT_12.RCC"
[23] "GSM5507815_Biopsy_before_NACT_15.RCC"
[24] "GSM5507818_Biopsy_before_NACT_18.RCC"
[25] "GSM5507820_Biopsy_before_NACT_20.RCC"
[26] "GSM5507821_Biopsy_before_NACT_21.RCC"
[27] "GSM5507823_Biopsy_before_NACT_23.RCC"
[28] "GSM5507824_Biopsy_before_NACT_24.RCC"
[29] "GSM5507825_Biopsy_before_NACT_25.RCC"
[30] "GSM5507826_Surgeny_after_NACT_1.RCC"
[31] "GSM5507828_Surgeny_after_NACT_3.RCC"
[32] "GSM5507829_Surgeny_after_NACT_4.RCC"
[33] "GSM5507830_Surgeny_after_NACT_5.RCC"
[34] "GSM5507831_Surgeny_after_NACT_6.RCC"
[35] "GSM5507833_Surgeny_after_NACT_8.RCC"
[36] "GSM5507834_Surgeny_after_NACT_9.RCC"
[37] "GSM5507835_Surgeny_after_NACT_10.RCC"
[38] "GSM5507836_Surgeny_after_NACT_11.RCC"
[39] "GSM5507837_Surgeny_after_NACT_12.RCC"
[40] "GSM5507838_Surgeny_after_NACT_13.RCC"
[41] "GSM5507839_Surgeny_after_NACT_14.RCC"
[42] "GSM5507840_Surgeny_after_NACT_15.RCC"
[43] "GSM5507841_Surgeny_after_NACT_16.RCC"
[44] "GSM5507842_Surgeny_after_NACT_17.RCC"
[45] "GSM5507843_Surgeny_after_NACT_18.RCC"
[46] "GSM5507844_Surgeny_after_NACT_19.RCC"

In [33]:
# get the vector for renaming (like a dictionary)
rename_vector = metadata$Name
# names are what is currrently in counts
names(rename_vector) = metadata$name

In [34]:
just_counts <- counts[,13:ncol(counts)]
colnames(just_counts)

 [1] "GSM5507801_Biopsy_before_NACT_1.RCC"
 [2] "GSM5507804_Biopsy_before_NACT_4.RCC"
 [3] "GSM5507805_Biopsy_before_NACT_5.RCC"
 [4] "GSM5507806_Biopsy_before_NACT_6.RCC"
 [5] "GSM5507807_Biopsy_before_NACT_7.RCC"
 [6] "GSM5507808_Biopsy_before_NACT_8.RCC"
 [7] "GSM5507809_Biopsy_before_NACT_9.RCC"
 [8] "GSM5507810_Biopsy_before_NACT_10.RCC"
 [9] "GSM5507811_Biopsy_before_NACT_11.RCC"
[10] "GSM5507812_Biopsy_before_NACT_12.RCC"
[11] "GSM5507815_Biopsy_before_NACT_15.RCC"
[12] "GSM5507818_Biopsy_before_NACT_18.RCC"
[13] "GSM5507820_Biopsy_before_NACT_20.RCC"
[14] "GSM5507821_Biopsy_before_NACT_21.RCC"
[15] "GSM5507823_Biopsy_before_NACT_23.RCC"
[16] "GSM5507824_Biopsy_before_NACT_24.RCC"
[17] "GSM5507825_Biopsy_before_NACT_25.RCC"
[18] "GSM5507826_Surgery_after_NACT_1.RCC"
[19] "GSM5507828_Surgery_after_NACT_3.RCC"
[20] "GSM5507829_Surgery_after_NACT_4.RCC"
[21] "GSM5507830_Surgery_after_NACT_5.RCC"
[22] "GSM5507831_Surgery_after_NACT_6.RCC"
[23] "GSM5507833_Surgery_after_NACT_8.RCC"
[24] "GSM5507834_Surgery_after_NACT_9.RCC"
[25] "GSM5507835_Surgery_after_NACT_10.RCC"
[26] "GSM5507836_Surgery_after_NACT_11.RCC"
[27] "GSM5507837_Surgery_after_NACT_12.RCC"
[28] "GSM5507838_Surgery_after_NACT_13.RCC"
[29] "GSM5507839_Surgery_after_NACT_14.RCC"
[30] "GSM5507840_Surgery_after_NACT_15.RCC"
[31] "GSM5507841_Surgery_after_NACT_16.RCC"
[32] "GSM5507842_Surgery_after_NACT_17.RCC"
[33] "GSM5507843_Surgery_after_NACT_18.RCC"
[34] "GSM5507844_Surgery_after_NACT_19.RCC"

In [35]:
just_raw_counts <- raw_counts[,11:ncol(raw_counts)]
colnames(just_raw_counts)

 [1] "GSM5507801_Biopsy_before_NACT_1.RCC"
 [2] "GSM5507802_Biopsy_before_NACT_2.RCC"
 [3] "GSM5507803_Biopsy_before_NACT_3.RCC"
 [4] "GSM5507804_Biopsy_before_NACT_4.RCC"
 [5] "GSM5507805_Biopsy_before_NACT_5.RCC"
 [6] "GSM5507806_Biopsy_before_NACT_6.RCC"
 [7] "GSM5507807_Biopsy_before_NACT_7.RCC"
 [8] "GSM5507808_Biopsy_before_NACT_8.RCC"
 [9] "GSM5507809_Biopsy_before_NACT_9.RCC"
[10] "GSM5507810_Biopsy_before_NACT_10.RCC"
[11] "GSM5507811_Biopsy_before_NACT_11.RCC"
[12] "GSM5507812_Biopsy_before_NACT_12.RCC"
[13] "GSM5507813_Biopsy_before_NACT_13.RCC"
[14] "GSM5507814_Biopsy_before_NACT_14.RCC"
[15] "GSM5507815_Biopsy_before_NACT_15.RCC"
[16] "GSM5507816_Biopsy_before_NACT_16.RCC"
[17] "GSM5507817_Biopsy_before_NACT_17.RCC"
[18] "GSM5507818_Biopsy_before_NACT_18.RCC"
[19] "GSM5507819_Biopsy_before_NACT_19.RCC"
[20] "GSM5507820_Biopsy_before_NACT_20.RCC"
[21] "GSM5507821_Biopsy_before_NACT_21.RCC"
[22] "GSM5507822_Biopsy_before_NACT_22.RCC"
[23] "GSM5507823_Biopsy_before_NACT_23.RCC"
[24] "GSM5507824_Biopsy_before_NACT_24.RCC"
[25] "GSM5507825_Biopsy_before_NACT_25.RCC"
[26] "GSM5507826_Surgery_after_NACT_1.RCC"
[27] "GSM5507827_Surgery_after_NACT_2.RCC"
[28] "GSM5507828_Surgery_after_NACT_3.RCC"
[29] "GSM5507829_Surgery_after_NACT_4.RCC"
[30] "GSM5507830_Surgery_after_NACT_5.RCC"
[31] "GSM5507831_Surgery_after_NACT_6.RCC"
[32] "GSM5507832_Surgery_after_NACT_7.RCC"
[33] "GSM5507833_Surgery_after_NACT_8.RCC"
[34] "GSM5507834_Surgery_after_NACT_9.RCC"
[35] "GSM5507835_Surgery_after_NACT_10.RCC"
[36] "GSM5507836_Surgery_after_NACT_11.RCC"
[37] "GSM5507837_Surgery_after_NACT_12.RCC"
[38] "GSM5507838_Surgery_after_NACT_13.RCC"
[39] "GSM5507839_Surgery_after_NACT_14.RCC"
[40] "GSM5507840_Surgery_after_NACT_15.RCC"
[41] "GSM5507841_Surgery_after_NACT_16.RCC"
[42] "GSM5507842_Surgery_after_NACT_17.RCC"
[43] "GSM5507843_Surgery_after_NACT_18.RCC"
[44] "GSM5507844_Surgery_after_NACT_19.RCC"

In [36]:
# Rename the columns in df1 that match the key-value pairs in df2
colnames(just_counts)[colnames(just_counts) %in% names(rename_vector)] <- rename_vector[colnames(just_counts)[colnames(just_counts) %in% names(rename_vector)]]
colnames(just_counts)

colnames(just_raw_counts)[colnames(just_raw_counts) %in% names(rename_vector)] <- rename_vector[colnames(just_raw_counts)[colnames(just_raw_counts) %in% names(rename_vector)]]
colnames(just_raw_counts)

 [1] "P1_Pre"   "P2_Pre"   "P17_Pre"  "P3_Pre"   "P4_Pre"   "P5_Pre"
 [7] "P6_Pre"   "P7_Pre"   "P8_Pre"   "P9_Pre"   "P10_Pre"  "P11_Pre"
[13] "P12_Pre"  "P13_Pre"  "P14_Pre"  "P15_Pre"  "P16_Pre"  "P1_Post"
[19] "P2_Post"  "P17_Post" "P3_Post"  "P4_Post"  "P5_Post"  "P6_Post"
[25] "P7_Post"  "P8_Post"  "P9_Post"  "P10_Post" "P11_Post" "P12_Post"
[31] "P13_Post" "P14_Post" "P15_Post" "P16_Post"

 [1] "P1_Pre"
 [2] "GSM5507802_Biopsy_before_NACT_2.RCC"
 [3] "GSM5507803_Biopsy_before_NACT_3.RCC"
 [4] "P2_Pre"
 [5] "P17_Pre"
 [6] "P3_Pre"
 [7] "P4_Pre"
 [8] "P5_Pre"
 [9] "P6_Pre"
[10] "P7_Pre"
[11] "P8_Pre"
[12] "P9_Pre"
[13] "GSM5507813_Biopsy_before_NACT_13.RCC"
[14] "GSM5507814_Biopsy_before_NACT_14.RCC"
[15] "P10_Pre"
[16] "GSM5507816_Biopsy_before_NACT_16.RCC"
[17] "GSM5507817_Biopsy_before_NACT_17.RCC"
[18] "P11_Pre"
[19] "GSM5507819_Biopsy_before_NACT_19.RCC"
[20] "P12_Pre"
[21] "P13_Pre"
[22] "GSM5507822_Biopsy_before_NACT_22.RCC"
[23] "P14_Pre"
[24] "P15_Pre"
[25] "P16_Pre"
[26] "P1_Post"
[27] "GSM5507827_Surgery_after_NACT_2.RCC"
[28] "P2_Post"
[29] "P17_Post"
[30] "P3_Post"
[31] "P4_Post"
[32] "GSM5507832_Surgery_after_NACT_7.RCC"
[33] "P5_Post"
[34] "P6_Post"
[35] "P7_Post"
[36] "P8_Post"
[37] "P9_Post"
[38] "P10_Post"
[39] "P11_Post"
[40] "P12_Post"
[41] "P13_Post"
[42] "P14_Post"
[43] "P15_Post"
[44] "P16_Post"

In [37]:
just_raw_counts <- as.data.frame(just_raw_counts)
just_counts <- as.data.frame(just_counts)

In [38]:
# Remove any counts with NA (so no pairings)
dim(just_counts)
dim(just_raw_counts)
just_counts <- just_counts[,colnames(just_counts)[!grepl("NA_", colnames(just_counts))]]
just_raw_counts <- just_raw_counts[,colnames(just_raw_counts)[!grepl("NA_", colnames(just_raw_counts))]]
dim(just_counts)
dim(just_raw_counts)

[1] 786  34

[1] 786  44

[1] 786  34

[1] 786  44

In [39]:
counts <- cbind(counts[,1:11], just_counts)
colnames(counts)

raw_counts <- cbind(raw_counts[,1:10], just_raw_counts)
colnames(raw_counts)
counts[1:2,]

 [1] "Probe Name"                "Annotation"
 [3] "Accession #"               "NS Probe ID"
 [5] "Class Name"                "Analyte Type"
 [7] "Target Sequence"           "% Samples above Threshold"
 [9] "Positive Flag"             "Avg Count"
[11] "Min Count"                 "P1_Pre"
[13] "P2_Pre"                    "P17_Pre"
[15] "P3_Pre"                    "P4_Pre"
[17] "P5_Pre"                    "P6_Pre"
[19] "P7_Pre"                    "P8_Pre"
[21] "P9_Pre"                    "P10_Pre"
[23] "P11_Pre"                   "P12_Pre"
[25] "P13_Pre"                   "P14_Pre"
[27] "P15_Pre"                   "P16_Pre"
[29] "P1_Post"                   "P2_Post"
[31] "P17_Post"                  "P3_Post"
[33] "P4_Post"                   "P5_Post"
[35] "P6_Post"                   "P7_Post"
[37] "P8_Post"                   "P9_Post"
[39] "P10_Post"                  "P11_Post"
[41] "P12_Post"                  "P13_Post"
[43] "P14_Post"                  "P15_Post"
[45] "P16_Post"

 [1] "Probe Name"
 [2] "Annotation"
 [3] "Accession #"
 [4] "NS Probe ID"
 [5] "Class Name"
 [6] "Analyte Type"
 [7] "% Samples above Threshold"
 [8] "Avg Count"
 [9] "Min Count"
[10] "Max Count"
[11] "P1_Pre"
[12] "GSM5507802_Biopsy_before_NACT_2.RCC"
[13] "GSM5507803_Biopsy_before_NACT_3.RCC"
[14] "P2_Pre"
[15] "P17_Pre"
[16] "P3_Pre"
[17] "P4_Pre"
[18] "P5_Pre"
[19] "P6_Pre"
[20] "P7_Pre"
[21] "P8_Pre"
[22] "P9_Pre"
[23] "GSM5507813_Biopsy_before_NACT_13.RCC"
[24] "GSM5507814_Biopsy_before_NACT_14.RCC"
[25] "P10_Pre"
[26] "GSM5507816_Biopsy_before_NACT_16.RCC"
[27] "GSM5507817_Biopsy_before_NACT_17.RCC"
[28] "P11_Pre"
[29] "GSM5507819_Biopsy_before_NACT_19.RCC"
[30] "P12_Pre"
[31] "P13_Pre"
[32] "GSM5507822_Biopsy_before_NACT_22.RCC"
[33] "P14_Pre"
[34] "P15_Pre"
[35] "P16_Pre"
[36] "P1_Post"
[37] "GSM5507827_Surgery_after_NACT_2.RCC"
[38] "P2_Post"
[39] "P17_Post"
[40] "P3_Post"
[41] "P4_Post"
[42] "GSM5507832_Surgery_after_NACT_7.RCC"
[43] "P5_Post"
[44] "P6_Post"
[45] "P7_Post"
[46] "P8_Post"
[47] "P9_Post"
[48] "P10_Post"
[49] "P11_Post"
[50] "P12_Post"
[51] "P13_Post"
[52] "P14_Post"
[53] "P15_Post"
[54] "P16_Post"

  Probe Name Annotation Accession # NS Probe ID Class Name Analyte Type
1            NA                     NA
2            NA                     NA
  Target Sequence % Samples above Threshold Positive Flag Avg Count ...
1 NA              NA                        NA            NA        ...
2 NA              NA                        NA            NA        ...
  P7_Post   P8_Post   P9_Post   P10_Post   P11_Post   P12_Post   P13_Post
1 true : P7 true : P8 true : P9 true : P10 true : P11 true : P12 true : P13
2
  P14_Post   P15_Post   P16_Post
1 true : P14 true : P15 true : P16
2

In [39]:
write.table(raw_counts, 
            "../Manso_GSE181597/data//counts/nSolver_rawcounts_cleanednames_05.30.25.txt", 
           row.names=FALSE, sep="\t", quote=FALSE)
write.table(counts, 
            "../Manso_GSE181597/data//counts/nSolver_normcounts_cleanednames_05.30.25.txt", 
           row.names=FALSE, sep="\t", quote=FALSE)
write.table(metadata, 
             "../Manso_GSE181597/data/counts/Manso_clean_metadata_05.30.25.txt", 
            quote=FALSE, sep="\t", row.names=FALSE)

## 3. Bitler

In [42]:
# read in the counts
counts <- fread("../Bitler_raw/nSolver_normcounts_all_Bitler_10.22.25.txt")
#clean_counts <- fread("../Bitler_raw/nSolver_normcounts_Bitler_9.16.25.txt")
counts[1:2,]
#clean_counts[1:2,]
# which of the samples have at least one sample with a flag for normalization
#setdiff(colnames(counts), colnames(clean_counts))

  Probe Name Annotation Accession #  NS Probe ID      Class Name Analyte Type
1 NEG_A      NA         ERCC_00096.1 ERCC_00096.1:230 Negative   SYSTEM
2 NEG_B      NA         ERCC_00041.1 ERCC_00041.1:440 Negative   SYSTEM
  Target Sequence
1 AACCGCCGCATACGGCCGATTGTCGCAGCCCGGGTCGATTATAACAACGGTGCAATCTCAGCTAAACCGACGCAGTTTTGCTCCTTGGATTCTGAGCCCG
2 GCACTGGCATTGGTCGTTTCAGGAGGCCATACAGAACTGGTTTATATGAAGGAACATGGATCATTTGAAGTCATTGGGGAAACCCTTGATGATGCGGCAG
  % Samples above Threshold Positive Flag Avg Count ...
1 0                         FALSE         8.47      ...
2 0                         FALSE         9.89      ...
  20230425_30102892141124-01_S22-26380 B7_10.RCC
1 12
2  6
  20230425_30102892141124-01_S22-2956 A2_05.RCC
1  8
2 28
  20240130_30102965471125-01_133_FN23-2466_Pre.RCC
1 15
2  7
  20240130_30102965471125-01_133_S23-35906_Post.RCC
1  7
2 10
  20240130_30102965471125-01_134_S23-12118_Post.RCC
1  8
2 24
  20240130_30102965471125-01_134_S23-400_Pre.RCC
1 15
2 19
  20240130_30102965471125-01_135_S23-20545_Post.RCC
1  7
2 15
  20240130_30102965471125-01_136_S23-8235_Pre.RCC
1 10
2 12
  20240130_30102965471125-01_138_FN23-1341_Pre.RCC
1 16
2 12
  20240130_30102965471125-01_138_S23-33135_Post.RCC
1 15
2 26

In [43]:
unique(grace_meta$Source)
table(grace_meta$Source)
grace_meta[1:2,]
bit_meta = grace_meta[grace_meta$Source %in% c("CU Anschutz, unpublished", "PMID:32928797"),]
# add Patient info
bit_meta$Patient <- paste0("P", seq(1, nrow(bit_meta)))
bit_meta[1:3,]

[1] "PMID:32928797"            "CU Anschutz, unpublished"
[3] "PMID:36131935"            "PMID:35087175"

CU Anschutz, unpublished            PMID:32928797            PMID:35087175
                      29                        6                       17
           PMID:36131935
                      31

  PRE SAMPLE ID
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
  POST SAMPLE ID                             Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55   8  1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
  PFS_high Chemo_status PFS_high_32928797 OS Death
1 0        1            0                 44 1
2 1        2            1                 51 0

  PRE SAMPLE ID
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
3 20191003_30102426300621-01_Sample05_05.RCC
  POST SAMPLE ID                             Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55   8  1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
3 20191003_30102426300621-01_Sample09_09.RCC PMID:32928797 56   3  1
  PFS_high Chemo_status PFS_high_32928797 OS Death Patient
1 0        1            0                 44 1     P1
2 1        2            1                 51 0     P2
3 0        0            0                 35 1     P3

In [44]:
# see if any values not found
setdiff(bit_meta[["PRE SAMPLE ID"]], colnames(counts))

setdiff(bit_meta[["POST SAMPLE ID"]], colnames(counts))

bit_meta[bit_meta[["PRE SAMPLE ID"]] %in% setdiff(bit_meta[["PRE SAMPLE ID"]], colnames(counts)),]

character(0)

character(0)

     PRE SAMPLE ID POST SAMPLE ID Source Age PFS Recurrence PFS_high
     Chemo_status PFS_high_32928797 OS Death Patient

In [45]:
# get the names to use
pre_bit = bit_meta[, c("PRE SAMPLE ID", "Patient")]
post_bit = bit_meta[, c("POST SAMPLE ID", "Patient")]
colnames(pre_bit) <- c("name", "Patient")
colnames(post_bit) <- c("name", "Patient")
pre_bit$Name <- paste0(pre_bit$Patient, "_Pre")
post_bit$Name <- paste0(post_bit$Patient, "_Post")
bit_meta2 <- rbind(pre_bit, post_bit)
table(bit_meta2$Patient)

 P1 P10 P11 P12 P13 P14 P15 P16 P17 P18 P19  P2 P20 P21 P22 P23 P24 P25 P26 P27
  2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2
P28 P29  P3 P30 P31 P32 P33 P34 P35  P4  P5  P6  P7  P8  P9
  2   2   2   2   2   2   2   2   2   2   2   2   2   2   2

In [46]:
# replace the sample names with the Patient and Pre and Post for simplicity purposes

# get the vector for renaming (like a dictionary)
rename_vector = bit_meta2$Name
# names are what is currrently in counts
names(rename_vector) = bit_meta2$name

In [47]:
counts[1:3,]

  Probe Name Annotation Accession #  NS Probe ID      Class Name Analyte Type
1 NEG_A      NA         ERCC_00096.1 ERCC_00096.1:230 Negative   SYSTEM
2 NEG_B      NA         ERCC_00041.1 ERCC_00041.1:440 Negative   SYSTEM
3 NEG_C      NA         ERCC_00019.1 ERCC_00019.1:140 Negative   SYSTEM
  Target Sequence
1 AACCGCCGCATACGGCCGATTGTCGCAGCCCGGGTCGATTATAACAACGGTGCAATCTCAGCTAAACCGACGCAGTTTTGCTCCTTGGATTCTGAGCCCG
2 GCACTGGCATTGGTCGTTTCAGGAGGCCATACAGAACTGGTTTATATGAAGGAACATGGATCATTTGAAGTCATTGGGGAAACCCTTGATGATGCGGCAG
3 GTACAGGCTGCTGGCTCATGTTTCCTTCTACGCTGCACTTGCGGGCATAGAGGTCGGTTGCGATCTATATTCGGAGATAACTATTCACCCAGCGCCACTC
  % Samples above Threshold Positive Flag Avg Count ...
1 0                         FALSE         8.47      ...
2 0                         FALSE         9.89      ...
3 0                         FALSE         9.10      ...
  20230425_30102892141124-01_S22-26380 B7_10.RCC
1 12
2  6
3  5
  20230425_30102892141124-01_S22-2956 A2_05.RCC
1  8
2 28
3  8
  20240130_30102965471125-01_133_FN23-2466_Pre.RCC
1 15
2  7
3 10
  20240130_30102965471125-01_133_S23-35906_Post.RCC
1  7
2 10
3 13
  20240130_30102965471125-01_134_S23-12118_Post.RCC
1  8
2 24
3  8
  20240130_30102965471125-01_134_S23-400_Pre.RCC
1 15
2 19
3  9
  20240130_30102965471125-01_135_S23-20545_Post.RCC
1  7
2 15
3 11
  20240130_30102965471125-01_136_S23-8235_Pre.RCC
1 10
2 12
3 13
  20240130_30102965471125-01_138_FN23-1341_Pre.RCC
1 16
2 12
3  9
  20240130_30102965471125-01_138_S23-33135_Post.RCC
1 15
2 26
3 26

In [48]:
just_counts <- counts[,13:ncol(counts)]
colnames(just_counts)

colnames(just_counts)[colnames(just_counts) %in% names(rename_vector)] <- rename_vector[colnames(just_counts)[colnames(just_counts) %in% names(rename_vector)]]
colnames(just_counts)

counts <- cbind(counts[,1], just_counts)
counts[1:2,]

 [1] "20191003_30102426300621-01_Sample01_01.RCC"
 [2] "20191003_30102426300621-01_Sample02_02.RCC"
 [3] "20191003_30102426300621-01_Sample03_03.RCC"
 [4] "20191003_30102426300621-01_Sample04_04.RCC"
 [5] "20191003_30102426300621-01_Sample05_05.RCC"
 [6] "20191003_30102426300621-01_Sample06_06.RCC"
 [7] "20191003_30102426300621-01_Sample07_07.RCC"
 [8] "20191003_30102426300621-01_Sample08_08.RCC"
 [9] "20191003_30102426300621-01_Sample09_09.RCC"
[10] "20191003_30102426300621-01_Sample10_10.RCC"
[11] "20191003_30102426300621-01_Sample11_11.RCC"
[12] "20191003_30102426300621-01_Sample12_12.RCC"
[13] "20221004_30102815640723-01_Sample01_01.RCC"
[14] "20221004_30102815640723-01_Sample02_02.RCC"
[15] "20221004_30102815640723-01_Sample03_03.RCC"
[16] "20221004_30102815640723-01_Sample04_04.RCC"
[17] "20221004_30102815640723-01_Sample05_05.RCC"
[18] "20221004_30102815640723-01_Sample06_06.RCC"
[19] "20221004_30102815640723-01_Sample08_08.RCC"
[20] "20221004_30102815640723-01_Sample09_09.RCC"
[21] "20221004_30102815640723-01_Sample11_11.RCC"
[22] "20221004_30102815640723-01_Sample12_12.RCC"
[23] "20221005_30102815650723-01_Sample01_01.RCC"
[24] "20221005_30102815650723-01_Sample02_02.RCC"
[25] "20221005_30102815650723-01_Sample04_04.RCC"
[26] "20221005_30102815650723-01_Sample05_05.RCC"
[27] "20221005_30102815650723-01_Sample06_06.RCC"
[28] "20221005_30102815650723-01_Sample08_08.RCC"
[29] "20221005_30102815650723-01_Sample09_09.RCC"
[30] "20221005_30102815650723-01_Sample10_10.RCC"
[31] "20221005_30102815650723-01_Sample11_11.RCC"
[32] "20221005_30102815650723-01_Sample12_12.RCC"
[33] "20221007_30102815660723-01_Sample01_01.RCC"
[34] "20221007_30102815660723-01_Sample03_03.RCC"
[35] "20221007_30102815660723-01_Sample04_04.RCC"
[36] "20221007_30102815660723-01_Sample05_05.RCC"
[37] "20221007_30102815660723-01_Sample06_06.RCC"
[38] "20221007_30102815660723-01_Sample07_07.RCC"
[39] "20221007_30102815660723-01_Sample08_08.RCC"
[40] "20221007_30102815660723-01_Sample09_09.RCC"
[41] "20230420_30102892131124-01_FN21-133 B1_11.RCC"
[42] "20230420_30102892131124-01_N22-1927 A1_05.RCC"
[43] "20230420_30102892131124-01_S16-23756 A3_01.RCC"
[44] "20230420_30102892131124-01_S16-2774 A1_07.RCC"
[45] "20230420_30102892131124-01_S16-5413 B2_08.RCC"
[46] "20230420_30102892131124-01_S16-8207 A6_03.RCC"
[47] "20230420_30102892131124-01_S17-19962 A1_02.RCC"
[48] "20230420_30102892131124-01_S21-16839 A15_09.RCC"
[49] "20230420_30102892131124-01_S21-7247 A4_12.RCC"
[50] "20230420_30102892131124-01_S21-7385 C3_04.RCC"
[51] "20230420_30102892131124-01_S22-12165 C1_10.RCC"
[52] "20230425_30102892141124-01_S15-9702 A2_02.RCC"
[53] "20230425_30102892141124-01_S16-11084 A8_07.RCC"
[54] "20230425_30102892141124-01_S16-14940 A2_04.RCC"
[55] "20230425_30102892141124-01_S16-17236 A1_12.RCC"
[56] "20230425_30102892141124-01_S17-26651 A1_01.RCC"
[57] "20230425_30102892141124-01_S21-718 C1_06.RCC"
[58] "20230425_30102892141124-01_S21-9998 B7_11.RCC"
[59] "20230425_30102892141124-01_S22-11443 A7_08.RCC"
[60] "20230425_30102892141124-01_S22-21920 C2_03.RCC"
[61] "20230425_30102892141124-01_S22-26380 B7_10.RCC"
[62] "20230425_30102892141124-01_S22-2956 A2_05.RCC"
[63] "20240130_30102965471125-01_133_FN23-2466_Pre.RCC"
[64] "20240130_30102965471125-01_133_S23-35906_Post.RCC"
[65] "20240130_30102965471125-01_134_S23-12118_Post.RCC"
[66] "20240130_30102965471125-01_134_S23-400_Pre.RCC"
[67] "20240130_30102965471125-01_135_S23-20545_Post.RCC"
[68] "20240130_30102965471125-01_136_S23-8235_Pre.RCC"
[69] "20240130_30102965471125-01_138_FN23-1341_Pre.RCC"
[70] "20240130_30102965471125-01_138_S23-33135_Post.RCC"

 [1] "P1_Post"  "P2_Post"  "P2_Pre"   "P1_Pre"   "P3_Pre"   "P4_Pre"
 [7] "P4_Post"  "P5_Pre"   "P3_Post"  "P6_Pre"   "P6_Post"  "P5_Post"
[13] "P7_Post"  "P19_Post" "P14_Post" "P10_Post" "P12_Pre"  "P10_Pre"
[19] "P13_Post" "P15_Post" "P18_Post" "P20_Post" "P11_Pre"  "P9_Post"
[25] "P8_Pre"   "P12_Post" "P20_Pre"  "P17_Post" "P8_Post"  "P13_Pre"
[31] "P16_Post" "P16_Pre"  "P9_Pre"   "P15_Pre"  "P18_Pre"  "P7_Pre"
[37] "P19_Pre"  "P14_Pre"  "P17_Pre"  "P11_Post" "P21_Pre"  "P22_Pre"
[43] "P25_Post" "P23_Pre"  "P24_Pre"  "P23_Post" "P31_Pre"  "P26_Post"
[49] "P26_Pre"  "P28_Post" "P29_Pre"  "P27_Pre"  "P24_Post" "P27_Post"
[55] "P25_Pre"  "P31_Post" "P28_Pre"  "P21_Post" "P30_Post" "P29_Post"
[61] "P22_Post" "P30_Pre"  "P32_Pre"  "P32_Post" "P33_Post" "P33_Pre"
[67] "P34_Post" "P34_Pre"  "P35_Pre"  "P35_Post"

  Probe Name P1_Post P2_Post P2_Pre P1_Pre P3_Pre P4_Pre P4_Post P5_Pre P3_Post
1 NEG_A       7      6       10     8      4      7      5       4      3
2 NEG_B      11      2        8     2      2      9      7       8      3
  ... P22_Post P30_Pre P32_Pre P32_Post P33_Post P33_Pre P34_Post P34_Pre
1 ... 12        8      15       7        8       15       7       10
2 ...  6       28       7      10       24       19      15       12
  P35_Pre P35_Post
1 16      15
2 12      26

In [49]:
write.table(counts, 
            "../Bitler_raw/nSolver_normcounts_all_cleanednames_10.22.25.txt", 
           row.names=FALSE, sep="\t", quote=FALSE)

In [50]:
colnames(bit_meta)
colnames(bit_meta) <- c("Pre_count_name", "Post_count_name", "Source", "Age", "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_3298797", "OS", "Death", "Patient")

bit_meta$Name_Source <- "Bitler"
bit_meta$Stage <- "NA"
bit_meta$PFI_mth <- "NA"
bit_meta$james_progression_status_4.25.22 <- "NA"
bit_meta$manso_response <- "NA"
bit_meta$CRS <- "NA"

 [1] "PRE SAMPLE ID"     "POST SAMPLE ID"    "Source"
 [4] "Age"               "PFS"               "Recurrence"
 [7] "PFS_high"          "Chemo_status"      "PFS_high_32928797"
[10] "OS"                "Death"             "Patient"

## 4. Combine metadata across all

In [51]:
colnames(metadat_wide)

metadat_wide_manso$Name_Source <- "Manso"
colnames(metadat_wide_manso)

 [1] "Post_count_name"            "Patient"
 [3] "age"                        "PFI_mth"
 [5] "progression_status_4.25.22" "Sex"
 [7] "Stage"                      "Pre_count_name"
 [9] "Source"                     "Age"
[11] "PFS"                        "Recurrence"
[13] "PFS_high"                   "Chemo_status"
[15] "PFS_high_32928797"          "OS"
[17] "Death"                      "Name_Source"

 [1] "Pre_count_name"       "True_Patient"         "response to nact:ch1"
 [4] "crs score:ch1"        "Post_count_name"      "Source"
 [7] "Age"                  "PFS"                  "Recurrence"
[10] "PFS_high"             "Chemo_status"         "PFS_high_32928797"
[13] "OS"                   "Death"                "Name_Source"

In [52]:
# see if any inconsistencies when double information
metadat_wide[metadat_wide$age != metadat_wide$Age,]

metadat_wide[metadat_wide$platinum_free_interval != metadat_wide$PFS,]

# for inconsistency, use the one provided by GEO

  Post_count_name                                       Patient age PFI_mth
2 GSM6068309_20210709_30102572870322-01_Sample12_12.RCC P2      62  14
  progression_status_4.25.22 Sex    Stage
2 yes                        female IIIC
  Pre_count_name                                        Source        Age PFS
2 GSM6068340_20210709_30102572870322-01_Sample03_03.RCC PMID:36131935 61  14
  Recurrence PFS_high Chemo_status PFS_high_32928797 OS Death Name_Source
2 1          1        2            NA                NA NA    James

     Post_count_name Patient age PFI_mth progression_status_4.25.22 Sex Stage
     Pre_count_name Source Age PFS Recurrence PFS_high Chemo_status
     PFS_high_32928797 OS Death Name_Source

In [53]:
metadat_wide = metadat_wide[,c("Patient", "age", "Pre_count_name", "Post_count_name", "Stage", "Source", "Name_Source", "PFI_mth",
                               "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_32928797", "OS", "Death", 
                               "progression_status_4.25.22")]
colnames(metadat_wide) <- c("Patient", "Age", "Pre_count_name", "Post_count_name", "Stage", "Source", "Name_Source", "PFI_mth",
                               "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_32928797", "OS", "Death", 
                               "james_progression_status_4.25.22")

metadat_wide_manso$Stage <- "NA"
metadat_wide_manso$PFI_mth <- "NA"
metadat_wide_manso = metadat_wide_manso[,c("True_Patient", "Age", "Pre_count_name", "Post_count_name", "Stage", "Source", "Name_Source", "PFI_mth", 
                                           "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_32928797", "OS", "Death", 
                                           "response to nact:ch1", "crs score:ch1")]
colnames(metadat_wide_manso) <- c("Patient", "Age", "Pre_count_name", "Post_count_name", "Stage", "Source", "Name_Source", "PFI_mth",
                               "PFS", "Recurrence", "PFS_high", "Chemo_status", "PFS_high_32928797", "OS", "Death", 
                               "manso_response", "CRS")

In [54]:
# combine
metadat_wide$manso_response <- "NA"
metadat_wide$CRS <- "NA"
metadat_wide_manso$james_progression_status_4.25.22 <- "NA"

metadata_full <- rbind(metadat_wide, metadat_wide_manso)

In [55]:
colnames(bit_meta)
colnames(metadata_full)

 [1] "Pre_count_name"                   "Post_count_name"
 [3] "Source"                           "Age"
 [5] "PFS"                              "Recurrence"
 [7] "PFS_high"                         "Chemo_status"
 [9] "PFS_high_3298797"                 "OS"
[11] "Death"                            "Patient"
[13] "Name_Source"                      "Stage"
[15] "PFI_mth"                          "james_progression_status_4.25.22"
[17] "manso_response"                   "CRS"

 [1] "Patient"                          "Age"
 [3] "Pre_count_name"                   "Post_count_name"
 [5] "Stage"                            "Source"
 [7] "Name_Source"                      "PFI_mth"
 [9] "PFS"                              "Recurrence"
[11] "PFS_high"                         "Chemo_status"
[13] "PFS_high_32928797"                "OS"
[15] "Death"                            "james_progression_status_4.25.22"
[17] "manso_response"                   "CRS"

In [56]:
metadata_full <- rbind(bit_meta, metadata_full, fill=TRUE)

In [57]:
metadata_full[1:4,]
table(metadata_full$Name_Source)

  Pre_count_name
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
3 20191003_30102426300621-01_Sample05_05.RCC
4 20191003_30102426300621-01_Sample06_06.RCC
  Post_count_name                            Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55   8  1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
3 20191003_30102426300621-01_Sample09_09.RCC PMID:32928797 56   3  1
4 20191003_30102426300621-01_Sample07_07.RCC PMID:32928797 48   9  1
  PFS_high Chemo_status PFS_high_3298797 OS Death Patient Name_Source Stage
1 0        1            0                44 1     P1      Bitler      NA
2 1        2            1                51 0     P2      Bitler      NA
3 0        0            0                35 1     P3      Bitler      NA
4 0        1            1                27 1     P4      Bitler      NA
  PFI_mth james_progression_status_4.25.22 manso_response CRS PFS_high_32928797
1 NA      NA                               NA             NA  NA
2 NA      NA                               NA             NA  NA
3 NA      NA                               NA             NA  NA
4 NA      NA                               NA             NA  NA

Bitler  James  Manso
    35     31     17

In [58]:
quantile(metadata_full$PFS)
quantile(metadata_full[metadata_full$Name_Source == "James",]$PFS)
quantile(metadata_full[metadata_full$Name_Source == "Manso",]$PFS)
quantile(metadata_full[metadata_full$Name_Source == "Bitler",]$PFS)

  0%  25%  50%  75% 100%
   0    6   10   18  132

  0%  25%  50%  75% 100%
 1.0  5.5 10.0 16.5 39.0

  0%  25%  50%  75% 100%
   1   11   18   71  132

  0%  25%  50%  75% 100%
 0.0  5.0  9.0 16.5 28.0

In [59]:
write.table(metadata_full, "../../Harmonization/Nanostring_metadata_10.22.25.txt", quote=FALSE, row.names=FALSE)

In [60]:
metadata_full[1:2,]

  Pre_count_name
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
  Post_count_name                            Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55   8  1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
  PFS_high Chemo_status PFS_high_3298797 OS Death Patient Name_Source Stage
1 0        1            0                44 1     P1      Bitler      NA
2 1        2            1                51 0     P2      Bitler      NA
  PFI_mth james_progression_status_4.25.22 manso_response CRS PFS_high_32928797
1 NA      NA                               NA             NA  NA
2 NA      NA                               NA             NA  NA

# Now RNA-seq

## Adzib

In [66]:
Adzib <- fread("../../RNASeq//Adzib/counts/Adzibolosu_metadata_09.11.24_withadded.txt")

Adzib$Treatment_status <- "NA"
Adzib[Adzib$time == "Post-Chemo",]$Treatment_status <- "Post"
Adzib[Adzib$time == "Pre-Chemo",]$Treatment_status <- "Pre"
Adzib$OS <- Adzib[["Overall survival"]]
Adzib$PFS <- Adzib[["Recurrence (months)"]]
Adzib$PFI_mth <- "NA"
Adzib[is.na(Adzib),] <- ""
Adzib[1:6,]

  geo_accession description title                                   time
1 GSM7091663    USF1_Pre    Late Recurrence, Patient 1, Pre-Chemo   Pre-Chemo
2 GSM7091664    USF1_Post   Late Recurrence, Patient 1, Post-Chemo  Post-Chemo
3 GSM7091665    USF3_Pre    Early Recurrence, Patient 1, Pre-Chemo  Pre-Chemo
4 GSM7091666    USF3_Post   Early Recurrence, Patient 1, Post-Chemo Post-Chemo
5 GSM7091667    USF7_Pre    Early Recurrence, Patient 2, Pre-Chemo  Pre-Chemo
6 GSM7091668    USF7_Post   Early Recurrence, Patient 2, Post-Chemo Post-Chemo
  patientid recurrence disease_state library_strategy SRR         Name
1 USF1      Late       HGSOC         RNA-Seq          SRR23803466 USF1_Pre
2 USF1      Late       HGSOC         RNA-Seq          SRR23803465 USF1_Post
3 USF3      Early      HGSOC         RNA-Seq          SRR23803464 USF3_Pre
4 USF3      Early      HGSOC         RNA-Seq          SRR23803463 USF3_Post
5 USF7      Early      HGSOC         RNA-Seq          SRR23803462 USF7_Pre
6 USF7      Early      HGSOC         RNA-Seq          SRR23803461 USF7_Post
  Recurrence (months) Overall survival PARP inhibitor Age V15 Treatment_status
1 14                                                          Pre
2                                                             Post
3 1.5                                                         Pre
4                                                             Post
5                                                             Pre
6                                                             Post
  OS PFS PFI_mth
1    14  NA
2        NA
3    1.5 NA
4        NA
5        NA
6        NA

In [67]:
# get into format comparable to grae metadata
metadat_wide_adzib <- Adzib %>%
  pivot_wider(
    id_cols = c(patientid),
    names_from = Treatment_status,
    values_from = SRR,
    names_prefix = "",
    names_glue = "{Treatment_status}_count_name"
  ) %>%
  left_join(
    Adzib %>%
      distinct(patientid, PFS, OS, Age, recurrence, PFI_mth), 
    by = "patientid"
  )
metadat_wide_adzib[order(metadat_wide_adzib$PFS),]

   patientid Pre_count_name Post_count_name PFS OS Age  recurrence PFI_mth
1  USF1      SRR23803466    SRR23803465                 Late       NA
2  USF3      SRR23803464    SRR23803463                 Early      NA
3  USF7      SRR23803462    SRR23803461                 Early      NA
4  USF10     SRR23803460    SRR23803459                 Late       NA
5  USF14     SRR23803458    SRR23803457                 Late       NA
6  USF15     SRR23803456    SRR23803455                 Early      NA
7  USF16     SRR23803454    SRR23803453                 Late       NA
8  USF17     SRR23803452    SRR23803451                 Early      NA
9  USF18     SRR23803450    SRR23803449                 Late       NA
10 WSU2      SRR23803448    SRR23803447                 Late       NA
11 WSU6      SRR23803446    SRR23803445                 Late       NA
12 WSU9      SRR23803444    SRR23803443                 Early      NA
13 WSU11     SRR23803442    SRR23803441                 Early      NA
14 WSU12     SRR23803440    SRR23803439                 Early      NA
15 WSU14     SRR23803438    SRR23803437                 Early      NA
16 USF31     SRR23803436    SRR23803435                 Late       NA
17 USF33     SRR23803434    SRR23803433                 Late       NA
18 USF34     SRR23803432    SRR23803431                 Late       NA
19 USF35     SRR23803430    SRR23803429                 Late       NA
20 USF36     SRR23803428    SRR23803427                 Early      NA
21 USF37     SRR23803426    SRR23803425                 Late       NA
22 USF39     SRR23803424    SRR23803423                 Early      NA
23 WSU_E     SRR23803422    SRR23803421                 Early      NA
24 WSU_F     SRR23803420    SRR23803419                 Late       NA
25 WSU11     SRR23803442    SRR23803441     0   12 66   Early      NA
26 WSU12     SRR23803440    SRR23803439     0   13 Died Early      NA
27 USF3      SRR23803464    SRR23803463     1.5         Early      NA
28 USF34     SRR23803432    SRR23803431     10          Late       NA
29 USF35     SRR23803430    SRR23803429     10          Late       NA
30 USF10     SRR23803460    SRR23803459     11          Late       NA
31 USF16     SRR23803454    SRR23803453     12          Late       NA
32 USF33     SRR23803434    SRR23803433     13          Late       NA
33 USF1      SRR23803466    SRR23803465     14          Late       NA
34 USF14     SRR23803458    SRR23803457     14          Late       NA
35 WSU_F     SRR23803420    SRR23803419     18  43 55   Late       NA
36 WSU6      SRR23803446    SRR23803445     22  29 67   Late       NA
37 WSU_E     SRR23803422    SRR23803421     4   47 59   Early      NA
38 WSU2      SRR23803448    SRR23803447     42  57      Late       NA
39 USF18     SRR23803450    SRR23803449     7           Late       NA

In [68]:
colnames(metadat_wide_adzib)
metadat_wide_adzib$Source <- "Adzib_2023"
metadat_wide_adzib$Name_Source <- "Adzib_2023"
metadat_wide_adzib$Recurrence <- "NA"
metadat_wide_adzib$PFS_high <- "NA"
metadat_wide_adzib$PFS_high_32928797 <- "NA"
metadat_wide_adzib$Chemo_status <- "NA"
metadat_wide_adzib$Death <- "NA"
metadat_wide_adzib$Stage <- "NA"
metadat_wide_adzib$manso_response <- "NA"
metadat_wide_adzib$CRS <- "NA"
metadat_wide_adzib$james_progression_status_4.25.22 <- "NA"
metadat_wide_adzib$Patient <- metadat_wide_adzib$patientid

[1] "patientid"       "Pre_count_name"  "Post_count_name" "PFS"
[5] "OS"              "Age"             "recurrence"      "PFI_mth"

In [69]:
table(metadata_full$PFS)
table(metadata_full$Recurrence)

unique(metadata_full[metadata_full$Recurrence == 1,]$PFS)
unique(metadata_full[metadata_full$Recurrence == 0,]$PFS)

  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  1   5   4   2   3   5   2   9   3   3   6   2   1   3   4   1   2   5   2   3
 20  22  24  26  27  28  31  39  50  54  71  91 103 109 132
  1   1   2   1   2   1   1   1   1   1   1   1   1   1   1

 0  1
14 69

 [1]  8 13  3  9 17 20 22  1  7  5 14  4 10 27 19  2 16 18 24 12  6 39 11 31 50
[26] 15 71

 [1]   0   1  28  10  13  19  24  26  17  91  54 103 109 132

In [70]:
setdiff(colnames(metadata_full), colnames(metadat_wide_adzib))

[1] "PFS_high_3298797"

In [71]:
dim(metadat_wide_adzib)
dim(metadat_wide_adzib[metadat_wide_adzib$PFS != "",])

[1] 39 20

[1] 15 20

In [73]:
metadata_full <- rbind(metadata_full, metadat_wide_adzib[,intersect(colnames(metadata_full), colnames(metadat_wide_adzib))], fill=TRUE)

In [74]:
dim(metadata_full)
metadata_full_test <- metadata_full
metadata_full[1:4,]

[1] 122  19

  Pre_count_name
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
3 20191003_30102426300621-01_Sample05_05.RCC
4 20191003_30102426300621-01_Sample06_06.RCC
  Post_count_name                            Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55  8   1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
3 20191003_30102426300621-01_Sample09_09.RCC PMID:32928797 56  3   1
4 20191003_30102426300621-01_Sample07_07.RCC PMID:32928797 48  9   1
  PFS_high Chemo_status PFS_high_3298797 OS Death Patient Name_Source Stage
1 0        1            0                44 1     P1      Bitler      NA
2 1        2            1                51 0     P2      Bitler      NA
3 0        0            0                35 1     P3      Bitler      NA
4 0        1            1                27 1     P4      Bitler      NA
  PFI_mth james_progression_status_4.25.22 manso_response CRS PFS_high_32928797
1 NA      NA                               NA             NA  NA
2 NA      NA                               NA             NA  NA
3 NA      NA                               NA             NA  NA
4 NA      NA                               NA             NA  NA

## Javella

In [75]:
jav_counts <- fread("../../NanoString-RNAseq-HGSOC/RNA-PrePost/data/final_counts/Jav_RNA_rpkm_nano_8.27.csv", sep=",")
jav_counts[1:2,]
jav_matrix <- as.matrix(jav_counts[,2:ncol(jav_counts)])
rownames(jav_matrix) <- jav_counts$V1

Warning message in fread("../../NanoString-RNAseq-HGSOC/RNA-PrePost/data/final_counts/Jav_RNA_rpkm_nano_8.27.csv", :
“Detected 40 column names but the data has 41 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”

  V1   PJ_1_Pre PJ_1_Post PJ_2_Pre PJ_2_Post PJ_5_Pre PJ_5_Post PJ_6_Pre
1 A2M  30.1154  86.2266   25.2580  68.7988    62.1897 87.5393   21.7785
2 APOE 45.2306  60.7965   17.1136  55.8698   118.8380 89.0494   35.0986
  PJ_6_Post PJ_12_Pre ⋯ PJ_43_Pre PJ_43_Post PJ_44_Pre PJ_44_Post PJ_45_Pre
1 25.8717   10.9029   ⋯ 22.6458   63.5309    109.0640  46.1092    49.9351
2 34.7592   29.2401   ⋯ 31.2506   96.4211     68.7194  23.6917    36.7304
  PJ_45_Post PJ_47_Pre PJ_47_Post PJ_49_Pre PJ_49_Post
1 46.7991    16.38070  28.8561    41.1993   101.0300
2 46.4002     9.79623  54.8413    68.6821    37.1434

In [76]:
# meta for microarray data
mic_meta <- as.data.frame(fread("../../Microarray/Javello_TS2_meta.csv", sep=","))
mic_meta$Patient <- paste0("PJ_", mic_meta[["Patient ID"]])
colnames(mic_meta)
mic_meta[1:2,]
mic_meta$PFS_mths <- mic_meta[['Progression free survival days']]/30
mic_meta$OS_mths <- mic_meta[['Overall survival days']]/30
mic_meta_add <- mic_meta[, c("Patient", "Patient deceased", "FIGO stage 2014", "Age at diagnosis", 
             "PFS_mths", "OS_mths", "Chemotherapy response score (CRS)", "Reccurence or Progression", "Adjuvant chemotherapy agent")]
colnames(mic_meta_add) <- c("Patient", "Death", "Stage", "Age", "PFS", "OS", "CRS", "Recurrence", "Chemo_regimen")
mic_meta_add[1:2,]   
mic_meta_add$Source <- "Jav_RNA"
mic_meta_add$Name_Source <- "Jav_RNA"

 [1] "Patient ID"
 [2] "DNA pair evaluable"
 [3] "RNA pair evaluable"
 [4] "Age at diagnosis"
 [5] "Ethnicity"
 [6] "Karnofsky score"
 [7] "FIGO stage 2014"
 [8] "Primary Tumor Site"
 [9] "Number of neoadjuvant chemotherapy cycles"
[10] "Days prior to debulking neoadjuvant chemotherapy started"
[11] "Debulking Status"
[12] "Chemotherapy response score (CRS)"
[13] "Adjuvant chemotherapy agent"
[14] "Number of adjuvant chemotherapy cycles"
[15] "Days after debulking surgery adjuvant chemotherapy started"
[16] "Adjuvant chemotherapy response"
[17] "Germline BRCA mutation status"
[18] "Reccurence or Progression"
[19] "Progression free survival days"
[20] "Platinum sensitivity"
[21] "Patient deceased"
[22] "Overall survival days"
[23] "V23"
[24] "Patient"

  Patient ID DNA pair evaluable RNA pair evaluable Age at diagnosis Ethnicity
1 2          Y                  Y                  56               Caucasian
2 5          Y                  Y                  62               Caucasian
  Karnofsky score FIGO stage 2014 Primary Tumor Site
1 90-100          IIIC            Ovary
2 90-100          IIIC            Fallopian Tube
  Number of neoadjuvant chemotherapy cycles
1 4
2 3
  Days prior to debulking neoadjuvant chemotherapy started ⋯
1 134                                                      ⋯
2  53                                                      ⋯
  Days after debulking surgery adjuvant chemotherapy started
1 45
2 22
  Adjuvant chemotherapy response Germline BRCA mutation status
1 Complete Response              BRCA 1
2 Partial Response               Negative
  Reccurence or Progression Progression free survival days Platinum sensitivity
1 Y                         561                            sensitive
2 Y                         309                            resistant
  Patient deceased Overall survival days V23 Patient
1 Y                1280                  NA  PJ_2
2 Y                 730                  NA  PJ_5

  Patient Death Stage Age PFS  OS       CRS Recurrence Chemo_regimen
1 PJ_2    Y     IIIC  56  18.7 42.66667 NA  Y          Carboplatin/Taxol
2 PJ_5    Y     IIIC  62  10.3 24.33333  1  Y          Carboplatin/Taxol

In [77]:
colnames(metadata_full_test)

 [1] "Pre_count_name"                   "Post_count_name"
 [3] "Source"                           "Age"
 [5] "PFS"                              "Recurrence"
 [7] "PFS_high"                         "Chemo_status"
 [9] "PFS_high_3298797"                 "OS"
[11] "Death"                            "Patient"
[13] "Name_Source"                      "Stage"
[15] "PFI_mth"                          "james_progression_status_4.25.22"
[17] "manso_response"                   "CRS"
[19] "PFS_high_32928797"

In [78]:
metadata_full <- rbindlist(list(metadata_full_test, mic_meta_add), fill = TRUE)

In [79]:
metadata_full[1:2,]

  Pre_count_name
1 20191003_30102426300621-01_Sample04_04.RCC
2 20191003_30102426300621-01_Sample03_03.RCC
  Post_count_name                            Source        Age PFS Recurrence
1 20191003_30102426300621-01_Sample01_01.RCC PMID:32928797 55  8   1
2 20191003_30102426300621-01_Sample02_02.RCC PMID:32928797 54  13  1
  PFS_high Chemo_status PFS_high_3298797 OS Death Patient Name_Source Stage
1 0        1            0                44 1     P1      Bitler      NA
2 1        2            1                51 0     P2      Bitler      NA
  PFI_mth james_progression_status_4.25.22 manso_response CRS PFS_high_32928797
1 NA      NA                               NA             NA  NA
2 NA      NA                               NA             NA  NA
  Chemo_regimen
1 NA
2 NA

In [80]:
dim(metadata_full)

colnames(metadata_full)
dim(metadata_full[metadata_full$PFS != "",])
dim(metadata_full[metadata_full$PFI_mth != "NA",])

[1] 162  20

 [1] "Pre_count_name"                   "Post_count_name"
 [3] "Source"                           "Age"
 [5] "PFS"                              "Recurrence"
 [7] "PFS_high"                         "Chemo_status"
 [9] "PFS_high_3298797"                 "OS"
[11] "Death"                            "Patient"
[13] "Name_Source"                      "Stage"
[15] "PFI_mth"                          "james_progression_status_4.25.22"
[17] "manso_response"                   "CRS"
[19] "PFS_high_32928797"                "Chemo_regimen"

[1] 134  20

[1] 31 20

In [81]:
write.table(metadata_full, "../../Harmonization/NonEGA_metadata_8.19.25.txt", quote=FALSE, row.names=FALSE, sep="\t")