# Comparing EGA metadata to published metadata

In [1]:
library(data.table)
library(stringr)
library(readxl)

Warning message:
“package ‘data.table’ was built under R version 4.4.1”

## 1. Reading in the EGA metadata

In [2]:
# Single cell
ega_sc_meta_runsamples <- fread("./EGA/SC_22_EGAD00001006922/run_sample.tsv")
ega_sc_meta_runsamples[1:2,]

ega_sc_meta_samplefile <- fread("./EGA/SC_22_EGAD00001006922/sample_file.tsv")
ega_sc_meta_samplefile[1:2,]

ega_sc_meta_sample <- fread("./EGA/SC_22_EGAD00001006922/samples.tsv")
ega_sc_meta_sample[1:2,]

dim(ega_sc_meta_samplefile)

  sample_alias           sample_accession_id biosample_id run_accession_id
1 EOC1005_postNACT_Tumor EGAN00002845446     SAMEA7893684 EGAR00002587078
2 EOC1005_postNACT_Tumor EGAN00002845446     SAMEA7893684 EGAR00002587079
  experiment_accession_id study_accession_id sample_attributes
1 EGAX00002366915         EGAS00001005006    ENA-CHECKLIST=ERC000026
2 EGAX00002366915         EGAS00001005006    ENA-CHECKLIST=ERC000026

  sample_accession_id sample_alias
1 EGAN00002845438     EOC349_postNACT_Omentum
2 EGAN00002845438     EOC349_postNACT_Omentum
  file_name                                    file_accession_id
1 EOC349_interval_Omentum_L002_R1_001.fastq.gz EGAF00004980381
2 EOC349_interval_Omentum_L002_R2_001.fastq.gz EGAF00004980382

  accession_id    alias                            title
1 EGAN00002845438 EOC349_postNACT_Omentum          \\N
2 EGAN00002845439 EOC349_treatmentNaive_Peritoneum \\N
  description                                          biological_sex
1 post-NACT sample collected from patient EOC349       female
2 treatment-naive sample collected from patient EOC349 female
  subject_id phenotype
1 EOC349     high-grade serous ovarian cancer
2 EOC349     high-grade serous ovarian cancer
  extra_attributes
1 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7893676"}]
2 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7893677"}]
  submission_accession_id created_at          edited_at
1 EGA00001814454          2021-01-30 12:57:45 2023-06-15 13:20:01
2 EGA00001814455          2021-01-30 12:58:02 2023-06-15 13:20:01

[1] 142   4

In [3]:
# Bulk
ega_meta_runsamples <- fread("./EGA/Bulk_200_EGAD00001006456/run_sample.tsv")
ega_meta_runsamples[1:2,]

ega_meta_samplefile <- fread("./EGA/Bulk_200_EGAD00001006456/sample_file.tsv")
ega_meta_samplefile[1:2,]

ega_meta_sample <- fread("./EGA/Bulk_200_EGAD00001006456/samples.tsv")
ega_meta_sample[1:2,]

dim(ega_meta_samplefile)

  sample_alias           sample_accession_id biosample_id run_accession_id
1 EOC1005_pPer1_RNA_seq6 EGAN00002747201     SAMEA7388782 EGAR00002430807
2 EOC1005_pPer1_RNA_seq6 EGAN00002747201     SAMEA7388782 EGAR00002431014
  experiment_accession_id study_accession_id sample_attributes
1 EGAX00002321824         EGAS00001004714    ENA-CHECKLIST=ERC000026
2 EGAX00002321824         EGAS00001004714    ENA-CHECKLIST=ERC000026

  sample_accession_id sample_alias
1 EGAN00002747201     EOC1005_pPer1_RNA_seq6
2 EGAN00002747201     EOC1005_pPer1_RNA_seq6
  file_name
1 EOC1005_pPer1_RNA_seq6_V100008511_L3_HK500HUMscnNAAHRAAPEI-509_1.fq.gz
2 EOC1005_pPer1_RNA_seq6_V100008511_L3_HK500HUMscnNAAHRAAPEI-509_2.fq.gz
  file_accession_id
1 EGAF00004723378
2 EGAF00004723379

  accession_id    alias                  title                  description
1 EGAN00002747201 EOC1005_pPer1_RNA_seq6 EOC1005_pPer1_RNA_seq6 \\N
2 EGAN00002747202 EOC1023_pOme_RNA_seq2  \\N                    \\N
  biological_sex subject_id phenotype
1 female         EOC1005    Cancer
2 female         EOC1023    Cancer
  extra_attributes
1 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388782"}]
2 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388783"}]
  submission_accession_id created_at          edited_at
1 EGA00001767977          2020-10-11 22:46:18 2023-06-15 13:19:13
2 EGA00001767978          2020-10-11 22:46:30 2023-06-15 13:19:13

[1] 658   4

In [4]:
length(sort(unique(ega_meta_sample$subject_id)))

length(sort(unique(ega_sc_meta_sample$subject_id)))

[1] 61

[1] 11

## Pietila 2021
* https://www.nature.com/articles/s41467-021-24009-8#MOESM4
* We have 56 patients with RNAseq samples confirmed to be found in the EGA as well. The remaining 12 patients do not have a corresponding RNAseq sample.
* We have 163 RNAseq samples

In [25]:
ega_meta_sample[1:2,]

  accession_id    alias                  title                  description
1 EGAN00002747201 EOC1005_pPer1_RNA_seq6 EOC1005_pPer1_RNA_seq6 \\N
2 EGAN00002747202 EOC1023_pOme_RNA_seq2  \\N                    \\N
  biological_sex subject_id phenotype
1 female         EOC1005    Cancer
2 female         EOC1023    Cancer
  extra_attributes
1 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388782"}]
2 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388783"}]
  submission_accession_id created_at          edited_at
1 EGA00001767977          2020-10-11 22:46:18 2023-06-15 13:19:13
2 EGA00001767978          2020-10-11 22:46:30 2023-06-15 13:19:13

In [32]:
pietilla_meta <- fread("./EGA_rel_data//Pietilla_2021_TS1.csv", sep=",")
pietilla_meta[1:2,]

cat("\nNumber of Patients", length(unique(pietilla_meta$EOC_ID)))
cat("\nNumber of Patients found in EGA", length(intersect(pietilla_meta$EOC_ID, ega_meta_sample$subject_id)))
sort(setdiff(pietilla_meta$EOC_ID, ega_meta_sample$subject_id))
unique(pietilla_meta[pietilla_meta$EOC_ID %in% setdiff(pietilla_meta$EOC_ID, ega_meta_sample$subject_id),]$RNASeq_ID)

cat("\nNumber of RNAseq samples", length(unique(setdiff(pietilla_meta$RNASeq_ID, ""))))
cat("\nNumber of RNAseq samples shared", length(intersect(pietilla_meta$RNASeq_ID, ega_meta_sample$alias)))

## NOW JUST NACT
cat("\n\n=====JUST NACT=====")
pietilla_meta = pietilla_meta[pietilla_meta$Treatment_strategy == "NACT" & pietilla_meta$RNASeq_ID != "",]

cat("\nNumber of Patients", length(unique(pietilla_meta$EOC_ID)))
cat("\nNumber of Patients found in EGA", length(intersect(pietilla_meta$EOC_ID, ega_meta_sample$subject_id)))
sort(setdiff(pietilla_meta$EOC_ID, ega_meta_sample$subject_id))

cat("\nNumber of RNAseq samples", length(unique(setdiff(pietilla_meta$RNASeq_ID, ""))))
cat("\nNumber of RNAseq samples shared", length(intersect(pietilla_meta$RNASeq_ID, ega_meta_sample$alias)))

  EOC_ID Histology Survival FIGO_stage Treatment_strategy
1 EOC26  HGSC      Deceased IIIC       NACT
2 EOC26  HGSC      Deceased IIIC       NACT
  Residual_tumor_after_DS Primary_chemo_regimen Primary_therapy_outcome
1 0                       CP-TX                 PD
2 0                       CP-TX                 PD
  Stage_of_sampling Sample  Progression_free_surviva_mths
1 Relapse           Ascites 4.17
2 Pre-chemo         Omentum 4.17
  Platinum_free_interval_days Overall_survival_mths Relapse_type IHC ex vivo
1 0                           12                    CP-resistant     x
2 0                           12
  RNASeq RNASeq_ID
1 x      EOC26_rAsc1_RNA2_seq3
2 x      EOC26_pOme1_RNA1_seq3

Number of Patients 68
Number of Patients found in EGA 56

 [1] "Control omentum_1" "Control omentum_2" "Control omentum_3"
 [4] "EOC197"            "EOC198"            "EOC481"
 [7] "EOC49"             "EOC691"            "EOC895"
[10] "EOC991"            "OCKI_p30"          "OCKI_p33"

[1] ""

Number of RNAseq samples 163
Number of RNAseq samples shared 154

=====JUST NACT=====
Number of Patients 38
Number of Patients found in EGA 38

character(0)

Number of RNAseq samples 116
Number of RNAseq samples shared 110

In [33]:
setdiff(pietilla_meta$RNASeq_ID, ega_meta_sample$alias)
unique(pietilla_meta$Stage_of_sampling)
unique(pietilla_meta$Treatment_strategy)
# How many patients have both Pre- chemo and Post-chemo
EOC_ID_list = c()
Type_list = c()
for (patient in unique(pietilla_meta$EOC_ID)) {
    # check what stage of sample has
    filt = pietilla_meta[pietilla_meta$EOC_ID == patient,]
    Type_list = c(Type_list, paste(unique(filt$Stage_of_sampling), collapse=";"))
    EOC_ID_list = c(EOC_ID_list, patient)
    }
sample_df = data.table("EOC_ID"=EOC_ID_list, "Samples"=Type_list)
sample_df[1:2,]
table(sample_df$Samples)

[1] "EOC677_iOvaR_RNA1_seq6a; EOC677_iOvaR_RNA1_seq6b"
[2] "EOC568_pMes1_RNA1_seq6a; EOC568_pMes1_RNA1_seq6b"
[3] "EOC1129_pAsc1_RNA1_seq6a; EOC1129_pAsc1_RNA1_seq6b"
[4] "EOC1129_pOvaR1_RNA1_seq6a; EOC1129_pOvaR1_RNA1_seq6b"
[5] "EOC3_iOme2_RNA1_seq6a; EOC3_iOme2_RNA1_seq6b"
[6] "EOC295_rAsc_RNA_seq6a; EOC295_rAsc_RNA_seq6b"

[1] "Relapse"    "Pre-chemo"  "Post-chemo"

[1] "NACT"

  EOC_ID Samples
1 EOC26  Relapse;Pre-chemo;Post-chemo
2 EOC891 Relapse;Pre-chemo

                  Post-chemo                    Pre-chemo
                           5                            7
        Pre-chemo;Post-chemo                      Relapse
                          17                            1
          Relapse;Post-chemo            Relapse;Pre-chemo
                           1                            4
Relapse;Pre-chemo;Post-chemo
                           3

In [8]:
sample_df[sample_df$Samples %in% c("Pre-chemo;Post-chemo", "Relapse;Pre-chemo;Post-chemo"),]$EOC_ID

 [1] "EOC26"   "EOC677"  "EOC218"  "EOC183"  "EOC568"  "EOC649"  "EOC376"
 [8] "EOC933"  "EOC1129" "EOC372"  "EOC423"  "EOC443"  "EOC883"  "EOC3"
[15] "EOC87"   "EOC136"  "EOC551"  "EOC60"   "EOC1133" "EOC868"

Only 20 samples have Pre-chemo and Post-chemo.

In [9]:
# Get the relevant metadata for those samples with pre and post chemo data
pietilla_meta_paired = pietilla_meta[pietilla_meta$EOC_ID %in% sample_df[sample_df$Samples %in% c("Pre-chemo;Post-chemo", 
                                                                           "Relapse;Pre-chemo;Post-chemo"),]$EOC_ID,]
pietilla_meta_paired = pietilla_meta_paired[pietilla_meta_paired$Stage_of_sampling %in% c("Pre-chemo", "Post-chemo"),]
dim(pietilla_meta_paired)

## More than 2 counts since multiple tissue types
table(pietilla_meta_paired$EOC_ID)



pietilla_meta_paired[1:4,]

[1] 77 18

EOC1129 EOC1133  EOC136  EOC183  EOC218   EOC26    EOC3  EOC372  EOC376  EOC423
      7       2       3       8       8       9       2       2       2       2
 EOC443  EOC551  EOC568   EOC60  EOC649  EOC677  EOC868   EOC87  EOC883  EOC933
      4       2       3       2       3       4       3       6       2       3

  EOC_ID Histology Survival FIGO_stage Treatment_strategy
1 EOC26  HGSC      Deceased IIIC       NACT
2 EOC26  HGSC      Deceased IIIC       NACT
3 EOC26  HGSC      Deceased IIIC       NACT
4 EOC26  HGSC      Deceased IIIC       NACT
  Residual_tumor_after_DS Primary_chemo_regimen Primary_therapy_outcome
1 0                       CP-TX                 PD
2 0                       CP-TX                 PD
3 0                       CP-TX                 PD
4 0                       CP-TX                 PD
  Stage_of_sampling Sample     Progression_free_surviva_mths
1 Pre-chemo         Omentum    4.17
2 Pre-chemo         Peritoneum 4.17
3 Pre-chemo         Peritoneum s
4 Pre-chemo         Primary    4.17
  Platinum_free_interval_days Overall_survival_mths Relapse_type IHC ex vivo
1 0                           12
2 0                           12
3 0                           12
4 0                           12
  RNASeq RNASeq_ID
1 x      EOC26_pOme1_RNA1_seq3
2 x      EOC26_pPer1_RNA2_seq3
3 x      EOC26_pPer2_RNA1_seq3
4 x      EOC26_pOvaL1_RNA2_seq3

### Zhang 2022
* https://doi.org//10.1126%2Fsciadv.abm1831

In [15]:
zhang_meta <- read_excel("./EGA_rel_data//Zhang_2022_11Pdata.xlsx")
zhang_meta[1:2,]
table(zhang_meta$Treatment)
zhang_meta = zhang_meta[zhang_meta$Treatment == "NACT",]
dim(zhang_meta)
length(unique(zhang_meta$Patient_ID))

  Patient_ID Age Treatment Stage PFI_days CRS CA125_Uperml_TN CA125_Uperml_PN
1 EOC1005    73  NACT      IVA   65       2   3776            343
2 EOC136     64  NACT      IVA   520      2   2647            212
  scRNA-seq TN scRNA-seq PN Bulk RNA-seq TN Bulk RNA-seq PN
1 Peritoneum   Tumor§       NA              NA
2 Mesentery    Omentum      NA              NA
  Bulk RNA-seq relapse RNA_Status
1 NA                   SC
2 NA                   SC

NACT  PDS
  29    1

[1] 29 14

[1] 29

In [16]:
length(intersect(pietilla_meta$EOC_ID, zhang_meta$Patient_ID))

[1] 26

### Lahtinen 2023
* https://doi.org/10.1016/j.ccell.2023.04.017

In [18]:
lahtinen_meta <- fread("./EGA_rel_data//Lahtinen_2023_TableS1.csv", sep=",", skip=1)
lahtinen_meta[1:3,]
unique(lahtinen_meta[["Treatment phase"]])
# remove the footnotes
lahtinen_meta = lahtinen_meta[grepl("^EOC", lahtinen_meta$Patient_ID),]
unique(lahtinen_meta[["Treatment phase"]])

  Patient_ID Sample_IDa    Sample type Treatment phase Tissue
1 EOC1005    EOC1005_pAsc1 Ascites     Diagnostic      Ascites
2 EOC1005    EOC1005_pOme1 Tissue      Diagnostic      Omentum
3 EOC1005    EOC1005_pPer1 Tissue      Diagnostic      Peritoneum
  Tissue group    genomic_profilingb phylogenetic_tree tumor_C_D
1 Ascites                            x                 x
2 Intra-abdominal                    x                 x
3 Intra-abdominal x                  x                 x
  evolution_states pathways_states treatment_effect RNA-seq PDOc Cohort
1 x                x                                x            Discovery
2 x                x                                x            Discovery
3 x                x                                x            Discovery

[1] "Diagnostic" "Relapse"    "Interval"   NA           ""

[1] "Diagnostic" "Relapse"    "Interval"   NA

## Launonen 2024
* https://pubmed.ncbi.nlm.nih.gov/39658541/
* Some of the data have previously been published and others not

In [19]:
Laun_meta = read_excel("./EGA_rel_data//Launonen_TS1_and_notes.xlsx")
Laun_meta[1:2,]
table(Laun_meta$Treatment_strategy)
Laun_meta = Laun_meta[Laun_meta$Treatment_strategy == "NACT",]
Laun_meta$Access[is.na(Laun_meta$Access)] <- "None"
table(Laun_meta$Access)
table(Laun_meta$Sample_type)

# How many patients have both Pre- chemo and Post-chemo
Pat_ID_list = c()
Type_list = c()
Access_list = c()
for (patient in unique(Laun_meta$Patient_code)) {
    # check what stage of sample has
    filt = Laun_meta[Laun_meta$Patient_code == patient,]
    Type_list = c(Type_list, paste(unique(filt$Sample_type), collapse=";"))
    Access_list = c(Access_list, paste(unique(filt$Access), collapse=";"))
    Pat_ID_list = c(Pat_ID_list, patient)
    }
Laun_sample_df = data.table("EOC_ID"=Pat_ID_list, "Samples"=Type_list, "Access"=Access_list)
Laun_sample_df[1:2,]
table(Laun_sample_df$Samples)

  Patient_code Sample_type Treatment_strategy OvaHRDscar BRCAmut_status
1 C033         IDS         NACT               HRP        BRCAwt
2 C033         chemo-naive NACT               HRP        BRCAwt
  PFI_category_12_months Stage_FIGO2014 tcycif  scRNAseq bulkRNAseq WGS(SBS3)
1 long                   IVB            omentum NA       omentum    NA
2 long                   IVB            omentum NA       NA         NA
  GeoMx   RNA_status Access
1 omentum Bulk       NA
2 omentum Neither    NA
  Notes
1 RNA-seq was originally published in and raw data can be accesssed via EGAS00001004714 which also cites this EGA but says clinical data can be found https://zenodo.org/records/7852210
2 Yellow columns were added by Hope

NACT  PDS
 112    5

                                         GSE266577
                                                21
           GSE266577, 10.1371/journal.pcbi.1009290
                                                 1
                               GSE266577, Hakkinen
                                                 2
                              GSE266577, Zhang2022
                                                18
GSE266577, Zhang2022; 10.1016/j.devcel.2023.04.012
                                                 3
                     GSE266577, Zhang2022;Hakkinen
                                                 1
                                              None
                                                66

chemo-naive         IDS
         44          68

  EOC_ID Samples         Access
1 C033   IDS;chemo-naive None
2 C063   IDS;chemo-naive None

    chemo-naive chemo-naive;IDS             IDS IDS;chemo-naive
              2               2              21              40

In [20]:
## 42 patients have both
Laun_meta_both <- Laun_meta[Laun_meta$Patient_code %in% 
                            Laun_sample_df[Laun_sample_df$Samples %in% c("chemo-naive;IDS", "IDS;chemo-naive"),]$EOC_ID,]
table(Laun_meta_both$Access)

Laun_sample_both_df = Laun_sample_df[Laun_sample_df$Samples %in% c("chemo-naive;IDS", "IDS;chemo-naive"),]
table(Laun_sample_both_df$Access)

                                         GSE266577
                                                20
           GSE266577, 10.1371/journal.pcbi.1009290
                                                 1
                               GSE266577, Hakkinen
                                                 1
                              GSE266577, Zhang2022
                                                18
GSE266577, Zhang2022; 10.1016/j.devcel.2023.04.012
                                                 3
                     GSE266577, Zhang2022;Hakkinen
                                                 1
                                              None
                                                41

                                                              GSE266577
                                                                      9
                                          GSE266577, Hakkinen;GSE266577
                                                                      1
                                                   GSE266577, Zhang2022
                                                                      8
                     GSE266577, Zhang2022; 10.1016/j.devcel.2023.04.012
                                                                      1
GSE266577, Zhang2022;GSE266577, Zhang2022; 10.1016/j.devcel.2023.04.012
                                                                      1
                     GSE266577, Zhang2022;GSE266577, Zhang2022;Hakkinen
                                                                      1
                      GSE266577;GSE266577, 10.1371/journal.pcbi.1009290
                                                                      1
                                                                   None
                                                                     20

Launonen provides 20 patients with both Chemo-naive and IDS samples that are not accessible anywhere else.

In [21]:
Laun_only_patients = Laun_sample_both_df[Laun_sample_both_df$Access == "None",]$EOC_ID
length(Laun_only_patients)

Laun_only_meta = Laun_meta[Laun_meta$Patient_code %in% Laun_only_patients,]
Laun_only_meta = Laun_only_meta[Laun_only_meta$RNA_status != "Neither",]

# Only keep those with samples from both

dim(Laun_only_meta)

[1] 20

[1] 36 15

## Now combine the above to get the full list of 
1. Patients and their clinical data
2. Samples with both Pre and Post NACT, Patient, etc.

In [22]:
# Get the list of all patients and then just combine all possible info
all_patients = union(Laun_only_meta$Patient_code, union(zhang_meta$Patient_ID,
                     union(lahtinen_meta$Patient_ID, pietilla_meta$EOC_ID)))
length(all_patients)

[1] 181

In [23]:
patients = c()
Age_list = c() # Zhang Age, 
Data_found_in = c()
OvaHRDscar = c() # Laun
BRCAmut_status = c() # Laun
PFI_12_months = c() # Launonen PFI_category_12_months

CRS = c() # Zhang CRS
CA125_Uperml_TN_PN = c() # Zhang CA125_Uperml_TN and PN

Survival = c() # Pietilla
Residual_tumor_after_DS = c() # Pietilla
Primary_chemo_regimen = c() # Pietilla
Progression_free_surviva_mths = c() # Pietilla
Overall_survival_mths = c() # Pietilla
Relapse_type = c() # Pietilla

PFI_days = c() # Zhang (PFI_days), Pietilla (Platinum_free_interval_days)
FIGO_Stage = c() # Laun Stage_FIGO2014, Zhang Stage, Pietilla FIGO_Stage
Tissues = c()  # Laun is bulkRNAseq, scRNAseq. Zhang is scRNA-seq TN, scRNA-seq PN, Bulk RNA-seq TN Bulk RNA-seq PN. Lahtinen is Tissue. Pietilla is Sample
Sample_stages = c() #Laun is Sample_type, Zhang is NA (all have it I believe), Lahtinen is Treatment phase, Pietilla is Stage_of_sampling
Response_to_Treatment = c() # Lahtinen_meta$treatment_effect (x or not), Pietilla_meta$Primary_therapy_outcome

for (patient in all_patients) {
    patients = c(patients, patient)
    # get patient info if in Launonen (can't be anywhere else)
    if (patient %in% Laun_only_meta$Patient_code) {
        filt = Laun_only_meta[Laun_only_meta$Patient_code == patient,]
        Data_found_in = c(Data_found_in, "Launonen_2024")
        Sample_stages = c(Sample_stages, paste(unique(filt$Sample_type), collapse=","))
        OvaHRDscar = c(OvaHRDscar, filt$OvaHRDscar[1])
        BRCAmut_status = c(BRCAmut_status, filt$BRCAmut_status[1])
        PFI_12_months = c(PFI_12_months, filt$PFI_category_12_months[1])
        FIGO_Stage = c(FIGO_Stage, filt$Stage_FIGO2014[1])
        Tissues = c(Tissues, paste(c(paste(unique(filt$bulkRNAseq), collapse=","), 
                                     paste(unique(filt$scRNAseq), collapse=",")), collapse=","))
        # Info Laun doesn't have
        Age_list = c(Age_list, "NotinData")
        CRS = c(CRS, "NotinData")
        CA125_Uperml_TN_PN = c(CA125_Uperml_TN_PN, "NotinData")
        Response_to_Treatment = c(Response_to_Treatment, "NotinData")
        PFI_days = c(PFI_days, "NotinData")
        Survival = c(Survival, "NotinData")
        Residual_tumor_after_DS = c(Residual_tumor_after_DS, "NotinData")
        Primary_chemo_regimen = c(Primary_chemo_regimen, "NotinData")
        Progression_free_surviva_mths = c(Progression_free_surviva_mths, "NotinData")
        Overall_survival_mths = c(Overall_survival_mths, "NotinData")
        Relapse_type = c(Relapse_type, "NotinData")
    } else {
        # if not in Launonen then
        OvaHRDscar = c(OvaHRDscar, "NotinData")
        BRCAmut_status = c(BRCAmut_status, "NotinData")
        PFI_12_months = c(PFI_12_months, "NotinData")
        Data_found_in_single = c()
        PFI_days_single = c()
        FIGO_Stage_single = c()
        Tissues_single = c()
        Sample_stages_single = c()
        Reponse_to_Treatment_single = c()
        # Consider possibility of multiple samples
        if (patient %in% zhang_meta$Patient_ID) {
            filt = zhang_meta[zhang_meta$Patient_ID == patient,]
            Data_found_in_single = c(Data_found_in_single, "Zhang_2022")
            PFI_days_single = c(PFI_days_single, filt$PFI_days[1])
            FIGO_Stage_single = c(FIGO_Stage_single, paste(unique(filt$Stage[1]), collapse=","))
            Tissues_single = c(Tissues_single, 
                               paste(c(paste(unique(filt[["scRNA-seq TN"]]), collapse=","), 
                                     paste(unique(filt[["scRNA-seq PN"]]), collapse=","), 
                                      paste(unique(filt[["Bulk RNA-seq TN"]]), collapse=","), 
                                     paste(unique(filt[["Bulk RNA-seq PN"]]), collapse=",")), collapse=","))
            Sample_stages_single = c(Sample_stages_single, "TN_PN")
            Age_list = c(Age_list, filt$Age[1])
            # Only Zhang
            CRS = c(CRS, filt$CRS[1])
            CA125_Uperml_TN_PN = c(CA125_Uperml_TN_PN, paste(filt$CA125_Uperml_TN[1], filt$CA125_Uperml_PN[1], collapse=","))
            } else {
            Age_list = c(Age_list, "NotinData")
            CRS = c(CRS, "NotinData")
            CA125_Uperml_TN_PN = c(CA125_Uperml_TN_PN, "NotinData")
        }
        if (patient %in% lahtinen_meta$Patient_ID) {
            filt = lahtinen_meta[lahtinen_meta$Patient_ID == patient,]
            Data_found_in_single = c(Data_found_in_single, "Lahtinen_2023")
            Tissues_single = c(Tissues_single, paste(unique(filt$Tissue), collapse=","))
            Sample_stages_single = c(Sample_stages_single, paste(unique(filt[["Treatment phase"]]), collapse=","))
            Reponse_to_Treatment_single = c(Reponse_to_Treatment_single, filt[["treatment_effect"]][1])
            } 
        # Get Pietilla Specific Info
        if (patient %in%  pietilla_meta$EOC_ID) {
            filt = pietilla_meta[pietilla_meta$EOC_ID == patient,]
            Data_found_in_single = c(Data_found_in_single, "Pietilla_2021")
            PFI_days_single = c(PFI_days_single, filt$Platinum_free_interval_days[1])
            FIGO_Stage_single = c(FIGO_Stage_single, paste(unique(filt$FIGO_stage[1]), collapse=","))
            Tissues_single = c(Tissues_single, paste(unique(filt$Sample), collapse=","))
            Sample_stages_single = c(Sample_stages_single, paste(unique(filt$Stage_of_sampling), collapse=","))
            Reponse_to_Treatment_single = c(Reponse_to_Treatment_single, paste(unique(filt$Primary_therapy_outcome), collapse=","))
            Survival = c(Survival, filt$Survival[1])
            Residual_tumor_after_DS = c(Residual_tumor_after_DS, paste(unique(filt$Residual_tumor_after_DS), collapse=","))
            Primary_chemo_regimen = c(Primary_chemo_regimen, paste(unique(filt$Primary_chemo_regimen), collapse=","))
            Progression_free_surviva_mths = c(Progression_free_surviva_mths, paste(unique(filt$Progression_free_surviva_mths), collapse=","))
            Overall_survival_mths = c(Overall_survival_mths, paste(unique(filt$Overall_survival_mths), collapse=","))
            Relapse_type = c(Relapse_type, paste(unique(filt$Relapse_type), collapse=","))
            } else {
            Survival = c(Survival, "NotinData")
            Residual_tumor_after_DS = c(Residual_tumor_after_DS, "NotinData")
            Primary_chemo_regimen = c(Primary_chemo_regimen, "NotinData")
            Progression_free_surviva_mths = c(Progression_free_surviva_mths, "NotinData")
            Overall_survival_mths = c(Overall_survival_mths, "NotinData")
            Relapse_type = c(Relapse_type, "NotinData")
            }
        # Get the final versions
        Data_found_in = c(Data_found_in, paste(Data_found_in_single, collapse=";"))
        PFI_days = c(PFI_days, paste(PFI_days_single, collapse=";"))
        FIGO_Stage = c(FIGO_Stage, paste(FIGO_Stage_single, collapse=";"))
        Tissues = c(Tissues, paste(Tissues_single, collapse=";"))
        Sample_stages = c(Sample_stages, paste(Sample_stages_single, collapse=";"))
        Response_to_Treatment = c(Response_to_Treatment, paste(Reponse_to_Treatment_single, collapse=";"))
    }
    
    # Check if any of the items are empty?
    }

cat(length(patients), length(Data_found_in), length(PFI_12_months), length(PFI_days), length(FIGO_Stage), 
   length(Tissues), length(Sample_stages), length(Response_to_Treatment), 
   length(Age_list), length(OvaHRDscar), length(Survival))
harmonized_patient_df = data.table("Patient"=patients, "Data_Found_In"=Data_found_in, 
                             "PlatFI_12_months"=PFI_12_months, "PlatFI_days"=PFI_days,
                             "FIGO_Stage"=FIGO_Stage, "Tissues"=Tissues, 
                             "Sample_stages"=Sample_stages, "Response_to_Treatment"=Response_to_Treatment,
                             "Age"=Age_list, "OvaHRDscar"=OvaHRDscar, "BRCAmut_status"=BRCAmut_status, 
                             "CRS"=CRS, "CA125_Uperml_TN_PN"=CA125_Uperml_TN_PN, 
                             "Piet21_Survival"=Survival, "Piet21Residual_tumor_after_DS"=Residual_tumor_after_DS, 
                             "Piet21_Primary_chemo_regimen"=Primary_chemo_regimen, 
                             "Piet21_Progression_free_survival_mths"=Progression_free_surviva_mths, 
                             "Piet21_Overall_survival_mths"=Overall_survival_mths, 
                             "Piet21_Relapse_type"=Relapse_type)
harmonized_patient_df[1:30,]
dim(harmonized_patient_df)

181 181 181 181 181 181 181 181 181 181 181

   Patient Data_Found_In                          PlatFI_12_months PlatFI_days
1  C033    Launonen_2024                          long             NotinData
2  C063    Launonen_2024                          long             NotinData
3  C129    Launonen_2024                          short            NotinData
4  C535    Launonen_2024                          long             NotinData
5  C686    Launonen_2024                          long             NotinData
6  S033    Launonen_2024                          short            NotinData
7  S034    Launonen_2024                          short            NotinData
8  S035    Launonen_2024                          short            NotinData
9  S036    Launonen_2024                          short            NotinData
10 S037    Launonen_2024                          short            NotinData
11 S038    Launonen_2024                          long             NotinData
12 S039    Launonen_2024                          short            NotinData
13 S040    Launonen_2024                          long             NotinData
14 S041    Launonen_2024                          short            NotinData
15 S042    Launonen_2024                          short            NotinData
16 S043    Launonen_2024                          short            NotinData
17 S044    Launonen_2024                          short            NotinData
18 S045    Launonen_2024                          short            NotinData
19 S046    Launonen_2024                          short            NotinData
20 S047    Launonen_2024                          short            NotinData
21 EOC1005 Zhang_2022;Lahtinen_2023;Pietilla_2021 NotinData        65;896b
22 EOC136  Zhang_2022;Lahtinen_2023;Pietilla_2021 NotinData        520;1006b
23 EOC153  Zhang_2022;Lahtinen_2023               NotinData        393
24 EOC227  Zhang_2022;Lahtinen_2023               NotinData        230
25 EOC3    Zhang_2022;Lahtinen_2023;Pietilla_2021 NotinData        14;14
26 EOC349  Zhang_2022                             NotinData        36
27 EOC372  Zhang_2022;Lahtinen_2023;Pietilla_2021 NotinData        460;1137b
28 EOC443  Zhang_2022;Lahtinen_2023;Pietilla_2021 NotinData        177;177
29 EOC540  Zhang_2022;Pietilla_2021               NotinData        126;126
30 EOC733  Zhang_2022;Lahtinen_2023;Pietilla_2021 NotinData        83;83
   FIGO_Stage
1  IVB
2  IIIC
3  IVB
4  IIIC
5  IVB
6  IVA
7  IIIC
8  IIIC
9  IIIC
10 IIIC
11 IIIC
12 IIIC
13 IVB
14 IVA
15 IIIC
16 IIIC
17 IIIC
18 IVA
19 IIIC
20 IIIC
21 IVA;IVA
22 IVA;IVA
23 IVA
24 IVA
25 IVA;IVA
26 IVB
27 IIIC;IIIC
28 IVA;IVA
29 IIIC;IIIC
30 IVA;IVA
   Tissues
1  omentum,NA
2  omentum,NA
3  omentum,NA
4  omentum,NA
5  ovary,NA
6  omentum,NA
7  omentum,NA
8  omentum,NA
9  omentum,NA
10 omentum,NA
11 omentum,NA
12 omentum,NA
13 omentum,NA
14 omentum,NA
15 omentum,NA
16 omentum,NA
17 omentum,NA
18 omentum,NA
19 omentum,NA
20 omentum,NA
21 Peritoneum,Tumor§,NA,NA;Ascites,Omentum,Peritoneum;Peritoneum
22 Mesentery,Omentum,NA,NA;Ascites,Mesenterium,Omentum,Ovary,Peritoneum;Mesentery,Omentum
23 Omentum,Omentum,NA,NA;Ascites,Omentum,Ovary,Peritoneum
24 Omentum§,Omentum§,NA,NA;Omentum,Ascites
25 Peritoneum§,Omentum,Peritoneum,Omentum;Omentum,Ovary,Peritoneum;Peritoneum,Omentum
26 Peritoneum§,Omentum§,NA,NA
27 Peritoneum,Peritoneum,Peritoneum,Peritoneum;Ascites,Omentum,Peritoneum;Peritoneum
28 Omentum,Omentum,Omentum,Omentum;Omentum,Ovary,Peritoneum;Omentum,Peritoneum,Primary
29 Omentum,Omentum,NA,NA;Omentum
30 Peritoneum,Omentum,NA,NA;Ascites,Omentum,Peritoneum;Peritoneum
   Sample_stages                                  Response_to_Treatment
1  IDS                                            NotinData
2  IDS                                            NotinData
3  IDS                                            NotinData
4  IDS                                            NotinData
5  IDS                                            NotinData
6  IDS,chemo-naive                                NotinData
7  IDS,chemo-naive                                NotinData
8  IDS,chemo-naive                                NotinData
9  IDS,chemo-naive                                NotinData
10 IDS,chemo-naive                                NotinData
11 IDS,chemo-naive                                NotinData
12 IDS,chemo-naive                                NotinData
13 IDS,chemo-naive                                NotinData
14 IDS,chemo-naive                                NotinData
15 IDS,chemo-naive                                NotinData
16 IDS,chemo-naive                                NotinData
17 IDS,chemo-naive                                NotinData
18 IDS,chemo-naive                                NotinData
19 IDS,chemo-naive                                NotinData
20 IDS,chemo-naive                                NotinData
21 TN_PN;Diagnostic;Pre-chemo                     ;PR
22 TN_PN;Diagnostic,Interval;Pre-chemo,Post-chemo ;CR
23 TN_PN;Diagnostic,Interval
24 TN_PN;Interval,Diagnostic,Relapse              x
25 TN_PN;Interval,Diagnostic;Pre-chemo,Post-chemo x;PD
26 TN_PN
27 TN_PN;Diagnostic,Interval;Pre-chemo,Post-chemo ;PR
28 TN_PN;Diagnostic,Interval;Pre-chemo,Post-chemo ;PR
29 TN_PN;Pre-chemo                                CR
30 TN_PN;Diagnostic,Interval;Pre-chemo            ;PR
   Age       OvaHRDscar BRCAmut_status CRS       CA125_Uperml_TN_PN
1  NotinData HRP        BRCAwt         NotinData NotinData
2  NotinData HRP        BRCAwt         NotinData NotinData
3  NotinData HRP        BRCAwt         NotinData NotinData
4  NotinData HRP        BRCAwt         NotinData NotinData
5  NotinData HRD        BRCAwt         NotinData NotinData
6  NotinData HRP        BRCAwt         NotinData NotinData
7  NotinData HRP        BRCAwt         NotinData NotinData
8  NotinData HRP        BRCAwt         NotinData NotinData
9  NotinData HRP        BRCAwt         NotinData NotinData
10 NotinData HRP        BRCAwt         NotinData NotinData
11 NotinData HRD        BRCAwt         NotinData NotinData
12 NotinData HRP        BRCAwt         NotinData NotinData
13 NotinData HRD        BRCAwt         NotinData NotinData
14 NotinData HRP        BRCAwt         NotinData NotinData
15 NotinData HRP        BRCAwt         NotinData NotinData
16 NotinData HRP        BRCAwt         NotinData NotinData
17 NotinData HRD        BRCAwt         NotinData NotinData
18 NotinData HRP        BRCAwt         NotinData NotinData
19 NotinData NA         NA             NotinData NotinData
20 NotinData NA         NA             NotinData NotinData
21 73        NotinData  NotinData      2         3776 343
22 64        NotinData  NotinData      2         2647 212
23 78        NotinData  NotinData      2         1063 93
24 74        NotinData  NotinData      2         445 33
25 67        NotinData  NotinData      2         821 221
26 67        NotinData  NotinData      2         2155 67
27 68        NotinData  NotinData      1         3180 334
28 54        NotinData  NotinData      3         2295 82
29 62        NotinData  NotinData      2         155 7
30 72        NotinData  NotinData      1         22079 s
   Piet21_Survival Piet21Residual_tumor_after_DS Piet21_Primary_chemo_regimen
1  NotinData       NotinData                     NotinData
2  NotinData       NotinData                     NotinData
3  NotinData       NotinData                     NotinData
4  NotinData       NotinData                     NotinData
5  NotinData       NotinData                     NotinData
6  NotinData       NotinData                     NotinData
7  NotinData       NotinData                     NotinData
8  NotinData       NotinData                     NotinData
9  NotinData       NotinData                     NotinData
10 NotinData       NotinData                     NotinData
11 NotinData       NotinData                     NotinData
12 NotinData       NotinData                     NotinData
13 NotinData       NotinData                     NotinData
14 NotinData       NotinData                     NotinData
15 NotinData       NotinData                     NotinData
16 NotinData       NotinData                     NotinData
17 NotinData       NotinData                     NotinData
18 NotinData       NotinData                     NotinData
19 NotinData       NotinData                     NotinData
20 NotinData       NotinData                     NotinData
21 Alive           1-10 mm                       CP-TX-BV
22 Alive           1-10 mm                       CP-TX
23 NotinData       NotinData                     NotinData
24 NotinData       NotinData                     NotinData
25 Deceased        1-10 mm                       CP-TX-BV
26 NotinData       NotinData                     NotinData
27 Alive           >10 mm                        CP-TX-BV
28 Deceased        0                             CP-TX
29 Deceased        0                             CP-TX
30 Deceased        1-10 mm                       CP-TX-BV
   Piet21_Progression_free_survival_mths Piet21_Overall_survival_mths
1  NotinData                             NotinData
2  NotinData                             NotinData
3  NotinData                             NotinData
4  NotinData                             NotinData
5  NotinData                             NotinData
6  NotinData                             NotinData
7  NotinData                             NotinData
8  NotinData                             NotinData
9  NotinData                             NotinData
10 NotinData                             NotinData
11 NotinData                             NotinData
12 NotinData                             NotinData
13 NotinData                             NotinData
14 NotinData                             NotinData
15 NotinData                             NotinData
16 NotinData                             NotinData
17 NotinData                             NotinData
18 NotinData                             NotinData
19 NotinData                             NotinData
20 NotinData                             NotinData
21 9.13                                  30b
22 23.83                                 34b
23 NotinData                             NotinData
24 NotinData                             NotinData
25 7.87                                  18
26 NotinData                             NotinData
27 23.37                                 38b
28 11.03                                 30
29 10.00                                 33
30 9.60                                  19
   Piet21_Relapse_type
1  NotinData
2  NotinData
3  NotinData
4  NotinData
5  NotinData
6  NotinData
7  NotinData
8  NotinData
9  NotinData
10 NotinData
11 NotinData
12 NotinData
13 NotinData
14 NotinData
15 NotinData
16 NotinData
17 NotinData
18 NotinData
19 NotinData
20 NotinData
21
22
23 NotinData
24 NotinData
25
26 NotinData
27
28
29
30

[1] 181  19

In [32]:
# check how many patients actually have both pre and post

pre <- harmonized_patient_df[grepl("chemo-naive|Pre-chemo|TN_PN|Diagnostic", harmonized_patient_df$Sample_stages),]
post <- harmonized_patient_df[grepl("IDS|Post-chemo|TN_PN|Interval", harmonized_patient_df$Sample_stages),]
nrow(pre)
nrow(post)

harmonized_patient_prepost_df <- harmonized_patient_df[harmonized_patient_df$Patient %in% intersect(pre$Patient, post$Patient),]


length(intersect(pre$Patient, post$Patient))
nrow(harmonized_patient_prepost_df)

[1] 170

[1] 76

[1] 66

[1] 66

In [33]:
table(harmonized_patient_prepost_df$Piet21_Overall_survival_mths)
table(harmonized_patient_prepost_df$Piet21_Relapse_type)

                 12        13        14        18        19        21        23
        1         1         1         2         1         1         1         2
       27        28     28,12        29        30       30b        31        33
        1         1         1         2         1         1         1         1
      34b        35       38b     39.8,       42b       43,       43b        54
        1         1         1         1         1         1         1         2
        9 NotinData
        1        37

              ,CP-resistant CP-resistant,     NotinData
           26             1             2            37

## See if the EGA can allow us to increase this number by considering more patients
* **Spoiler**: It doesn't. In fact it only has 23 patients with paired bulk RNA-seq samples, and 11 patients with paired scRNA-seq amples, although the number of paired samples per patient is higher. A total of 29 patients compared to ours at 66 (48 perfect matches as observed further below).

In [34]:
ega_sc_meta_sample[1,]
split <- str_split_fixed(ega_sc_meta_sample$alias, "_", 3)
ega_sc_meta_sample$patient_id <- split[,1]
ega_sc_meta_sample$Sample_Stage <- split[,2]
ega_sc_meta_sample$Tissue <- split[,3]
ega_sc_meta_sample[1:3,]

  accession_id    alias                   title
1 EGAN00002845438 EOC349_postNACT_Omentum \\N
  description                                    biological_sex subject_id
1 post-NACT sample collected from patient EOC349 female         EOC349
  phenotype
1 high-grade serous ovarian cancer
  extra_attributes
1 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7893676"}]
  submission_accession_id created_at          edited_at
1 EGA00001814454          2021-01-30 12:57:45 2023-06-15 13:20:01

  accession_id    alias                            title
1 EGAN00002845438 EOC349_postNACT_Omentum          \\N
2 EGAN00002845439 EOC349_treatmentNaive_Peritoneum \\N
3 EGAN00002845440 EOC227_postNACT_Omentum          \\N
  description                                          biological_sex
1 post-NACT sample collected from patient EOC349       female
2 treatment-naive sample collected from patient EOC349 female
3 post-NACT sample collected from patient EOC227       female
  subject_id phenotype
1 EOC349     high-grade serous ovarian cancer
2 EOC349     high-grade serous ovarian cancer
3 EOC227     high-grade serous ovarian cancer
  extra_attributes
1 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7893676"}]
2 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7893677"}]
3 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7893678"}]
  submission_accession_id created_at          edited_at           patient_id
1 EGA00001814454          2021-01-30 12:57:45 2023-06-15 13:20:01 EOC349
2 EGA00001814455          2021-01-30 12:58:02 2023-06-15 13:20:01 EOC349
3 EGA00001814456          2021-01-30 12:58:44 2023-06-15 13:20:01 EOC227
  Sample_Stage   Tissue
1 postNACT       Omentum
2 treatmentNaive Peritoneum
3 postNACT       Omentum

In [35]:
ega_meta_sample[1,]
split <- str_split_fixed(ega_meta_sample$alias, "_", 4)
ega_meta_sample$patient_id <- split[,1]
ega_meta_sample$Tissue_Stage <- split[,2]
ega_meta_sample$Seq_num <- split[,4]
#table(ega_meta_sample$Tissue_Stage)




ega_meta_sample$Tissue <- sub(".", '', ega_meta_sample$Tissue_Stage)
ega_meta_sample[grepl("Ome", ega_meta_sample$Tissue_Stage),]$Tissue <- "Omentum"
ega_meta_sample[grepl("Asc", ega_meta_sample$Tissue_Stage),]$Tissue <- "Ascites"
ega_meta_sample[grepl("Mes", ega_meta_sample$Tissue_Stage),]$Tissue <- "Mesentary"
ega_meta_sample[grepl("Ova", ega_meta_sample$Tissue_Stage),]$Tissue <- "Ovary"
ega_meta_sample[grepl("OvaL", ega_meta_sample$Tissue_Stage),]$Tissue <- "LeftOvary"
ega_meta_sample[grepl("OvaR", ega_meta_sample$Tissue_Stage),]$Tissue <- "RightOvary"
ega_meta_sample[grepl("Per", ega_meta_sample$Tissue_Stage),]$Tissue <- "Peritoneum"
ega_meta_sample[grepl("Tum", ega_meta_sample$Tissue_Stage),]$Tissue <- "Tumor"
ega_meta_sample[grepl("Tub", ega_meta_sample$Tissue_Stage),]$Tissue <- "Tube"
ega_meta_sample[grepl("Oth", ega_meta_sample$Tissue_Stage),]$Tissue <- "Other"
ega_meta_sample[grepl("Bow", ega_meta_sample$Tissue_Stage),]$Tissue <- "Bowel"
ega_meta_sample[grepl("Adn", ega_meta_sample$Tissue_Stage),]$Tissue <- "Adnexa"
ega_meta_sample[grepl("AdnL", ega_meta_sample$Tissue_Stage),]$Tissue <- "LeftAdnexa"
ega_meta_sample[grepl("AdnR", ega_meta_sample$Tissue_Stage),]$Tissue <- "RightAdnexa"
ega_meta_sample[grepl("LN", ega_meta_sample$Tissue_Stage),]$Tissue <- "LymphNode"
ega_meta_sample[grepl("LNL", ega_meta_sample$Tissue_Stage),]$Tissue <- "LeftLymphNode"
ega_meta_sample[grepl("LNR", ega_meta_sample$Tissue_Stage),]$Tissue <- "RightLymphNode"
ega_meta_sample$Sample_Stage <- ""
ega_meta_sample[grepl("^i", ega_meta_sample$Tissue_Stage),]$Sample_Stage <- "Interval/Post-Chemo"
ega_meta_sample[grepl("^p", ega_meta_sample$Tissue_Stage),]$Sample_Stage <- "Pre-Chemo"
ega_meta_sample[grepl("^r", ega_meta_sample$Tissue_Stage),]$Sample_Stage <- "Relapse"

table(ega_meta_sample$Tissue)
ega_meta_sample[12:14,]
table(ega_meta_sample$Sample_Stage)

  accession_id    alias                  title                  description
1 EGAN00002747201 EOC1005_pPer1_RNA_seq6 EOC1005_pPer1_RNA_seq6 \\N
  biological_sex subject_id phenotype
1 female         EOC1005    Cancer
  extra_attributes
1 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388782"}]
  submission_accession_id created_at          edited_at
1 EGA00001767977          2020-10-11 22:46:18 2023-06-15 13:19:13

       Ascites          Bowel     LeftAdnexa  LeftLymphNode      LeftOvary
            36              1              4              3             11
     LymphNode      Mesentary        Omentum          Other          Ovary
             2             17             50              2              8
    Peritoneum    RightAdnexa RightLymphNode     RightOvary           Tube
            39              1              2             26              4
         Tumor           Ute1
             4              2

  accession_id    alias                   title description biological_sex
1 EGAN00002747213 EOC649_iOme1_RNA2_seq5  \\N   \\N         female
2 EGAN00002747214 EOC740_iOvaR1_RNA1_seq5 \\N   \\N         female
3 EGAN00002747215 EOC649_pOme1_RNA2_seq5  \\N   \\N         female
  subject_id phenotype
1 EOC649     Cancer
2 EOC740     Cancer
3 EOC649     Cancer
  extra_attributes
1 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388794"}]
2 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388795"}]
3 [{"tag": "ENA-CHECKLIST", "unit": null, "value": "ERC000026"}, {"tag": "biosample_id", "value": "SAMEA7388796"}]
  submission_accession_id created_at          edited_at           patient_id
1 EGA00001767989          2020-10-11 23:08:06 2023-06-15 13:19:13 EOC649
2 EGA00001767990          2020-10-11 23:08:10 2023-06-15 13:19:13 EOC740
3 EGA00001767991          2020-10-11 23:08:12 2023-06-15 13:19:13 EOC649
  Tissue_Stage Seq_num Tissue     Sample_Stage
1 iOme1        seq5    Omentum    Interval/Post-Chemo
2 iOvaR1       seq5    RightOvary Interval/Post-Chemo
3 pOme1        seq5    Omentum    Pre-Chemo

Interval/Post-Chemo           Pre-Chemo             Relapse
                 65                 126                  21

In [36]:
# Only consider patients on which we have metadata
ega_meta_sample_patients <- ega_meta_sample[ega_meta_sample$patient_id %in% all_patients,]
dim(ega_meta_sample_patients)
table(ega_meta_sample_patients$Sample_Stage)

pre_ega <- ega_meta_sample_patients[ega_meta_sample_patients$Sample_Stage == "Pre-Chemo",]$patient_id
post_ega <- ega_meta_sample_patients[ega_meta_sample_patients$Sample_Stage == "Interval/Post-Chemo",]$patient_id
length(intersect(pre_ega, post_ega))



ega_sc_meta_sample <- ega_sc_meta_sample[ega_sc_meta_sample$patient_id %in% all_patients,]
table(ega_sc_meta_sample$Sample_Stage)
pre_sc_ega <- ega_sc_meta_sample[ega_sc_meta_sample$Sample_Stage == "treatmentNaive",]$patient_id
post_sc_ega <- ega_sc_meta_sample[ega_sc_meta_sample$Sample_Stage == "postNACT",]$patient_id
length(intersect(pre_sc_ega, post_sc_ega))

[1] 202  16

Interval/Post-Chemo           Pre-Chemo             Relapse
                 64                 117                  21

[1] 23

      postNACT treatmentNaive
            11             12

[1] 11

In [37]:
# Do we have any EGA data that isn't found in what we have so far?
length(union(intersect(pre_ega, post_ega), intersect(pre_sc_ega, post_sc_ega)))
length(intersect(pre_sc_ega, post_sc_ega))
length(intersect(pre_ega, post_ega))
setdiff(intersect(pre_ega, post_ega), harmonized_patient_prepost_df$Patient)
setdiff(intersect(pre_sc_ega, post_sc_ega), harmonized_patient_prepost_df$Patient)

[1] 29

[1] 11

[1] 23

character(0)

character(0)

### Now get the RNA-seq sources (papers) for each of the patients
* Launonen is at the sample level
* Zhang is at the patient level
* Lahtinen is at the sample level

* Tissue
* Bulk or SC (Launonen: RNA_status, scRNAseq, bulkRNAseq), Zhang: scRNA-seq TN, ... RNA_Status
* Sample Type (IDS vs chemo-naive)
* Sample ID (Lahtinen_meta$Sample_IDa, pie: RNASeq_ID)

In [38]:
patients = c()
Tissue_list = c()  # Laun is bulkRNAseq, scRNAseq. Zhang is scRNA-seq TN, scRNA-seq PN, Bulk RNA-seq TN Bulk RNA-seq PN. Lahtinen is Tissue. Pietilla is Sample
RNAType_list = c()
Data_found_in = c()
RNAseqID = c()
Sample_stages = c() #Laun is Sample_type, Zhang is NA (all have it I believe), Lahtinen is Treatment phase, Pietilla is Stage_of_sampling


for (patient in all_patients) {
    # get patient info if in Launonen (can't be anywhere else)
    if (patient %in% Laun_only_meta$Patient_code) {
        filt = Laun_only_meta[Laun_only_meta$Patient_code == patient,]
        for (index in seq(1, nrow(filt))) {
             Data_found_in = c(Data_found_in, "Launonen_2024")
             Sample_stages = c(Sample_stages, filt$Sample_type[index])
             RNAType_list = c(RNAType_list, filt$RNA_status[index])
             RNAseqID = c(RNAseqID, NA)
             Tissue_list = c(Tissue_list, filt$bulkRNAseq[index])
             patients = c(patients, patient)
            } }
    if (patient %in% zhang_meta$Patient_ID) {
        filt = zhang_meta[zhang_meta$Patient_ID == patient,]
        Data_found_in = c(Data_found_in, "Zhang_2022", "Zhang_2022")
        Sample_stages = c(Sample_stages, "Treatment-Naive", "Post-NACT")
        #### RNAseqID = c(RNAseqID, NA)
        patients = c(patients, patient, patient)
        RNAseqID = c(RNAseqID, NA, NA)
        for (index in seq(1, nrow(filt))) {
            if (is.na(filt[["scRNA-seq TN"]][index])) {
            Tissue_list = c(Tissue_list, filt[["scRNA-seq TN"]][index], filt[["scRNA-seq PN"]][index])
            RNAType_list = c(RNAType_list, "SC", "SC")
            } else {
            Tissue_list = c(Tissue_list, filt[["Bulk RNA-seq TN"]][index], filt[["Bulk RNA-seq PN"]][index])
            RNAType_list = c(RNAType_list, "Bulk", "Bulk")
            }}
        }
             
     if (patient %in% lahtinen_meta$Patient_ID) {
        filt = lahtinen_meta[lahtinen_meta$Patient_ID == patient,]
        for (index in seq(1, nrow(filt))) {
            patients = c(patients, patient)
            Data_found_in = c(Data_found_in, "Lahtinen_2023")
            RNAType_list = c(RNAType_list, "Bulk")
            Tissue_list = c(Tissue_list, filt$Tissue[index])
            RNAseqID = c(RNAseqID, filt$Sample_IDa[index])
            Sample_stages = c(Sample_stages, filt[["Treatment phase"]][index])
            }}
             
     if (patient %in% pietilla_meta$EOC_ID) {
        filt = pietilla_meta[pietilla_meta$EOC_ID == patient,]
        for (index in seq(1, nrow(filt))) {
            patients = c(patients, patient)
            RNAseqID = c(RNAseqID, filt$RNASeq_ID[index])
            Data_found_in = c(Data_found_in, "Pietilla_2021")
            RNAType_list = c(RNAType_list, "Bulk")
            Tissue_list = c(Tissue_list, filt$Sample[index])
            Sample_stages = c(Sample_stages, filt[["Stage_of_sampling"]][index])
            }}
}


cat(length(patients), length(Tissue_list), length(RNAType_list), length(Data_found_in), length(RNAseqID), 
   length(Sample_stages))
harmonized_sample_df = data.table("Patient"=patients, "Data_Found_In"=Data_found_in, 
                             "Assay"=RNAType_list, "Tissue"=Tissue_list, 
                             "RNAseqID"=RNAseqID, "Stage"=Sample_stages)

unique(harmonized_sample_df$Stage)
# get harmonized names for stage
harmonized_sample_df[harmonized_sample_df$Stage %in% c("chemo-naive", "Treatment-Naive", 
                                                      "Diagnostic", "Pre-chemo"),]$Stage <- "PreNACT"
harmonized_sample_df[harmonized_sample_df$Stage %in% c("Post-NACT", "Interval", 
                                                      "IDS", "Post-chemo"),]$Stage <- "PostNACT"
#harmonized_sample_df
harmonized_sample_df$Comb_Name_Tissue <- paste0(harmonized_sample_df$Patient, "_", harmonized_sample_df$Tissue, "_",
                                        harmonized_sample_df$Stage, "_",harmonized_sample_df$Assay)
harmonized_sample_df$Comb_Name <- paste0(harmonized_sample_df$Patient, "_", 
                                        harmonized_sample_df$Stage, "_",harmonized_sample_df$Assay)
#table(harmonized_sample_df$Comb_Name)
dim(harmonized_sample_df)


# How many samples have a twin (Same everything except Pre vs Post)
Twin_list = c()
Twin_bool_list = c()
Exact_Twin_list = c()
Exact_Twin_bool_list = c()

for (index in seq(1, nrow(harmonized_sample_df))) {
    name = harmonized_sample_df$Comb_Name[index]
    exact_name = harmonized_sample_df$Comb_Name_Tissue[index]
    stage = harmonized_sample_df$Stage[index]
    if (is.na(stage)) {
        Twin_list = c(Twin_list, NA)
        Twin_bool_list = c(Twin_bool_list, NA)
        Exact_Twin_list = c(Exact_Twin_list, NA)
        Exact_Twin_bool_list = c(Exact_Twin_bool_list, NA)
        } else if (stage == "PreNACT") {
         twin = harmonized_sample_df[harmonized_sample_df$Comb_Name == sub("Pre", "Post", name),]
         if (nrow(twin) > 0) {
             Twin_list = c(Twin_list, twin$Comb_Name[1])
             Twin_bool_list = c(Twin_bool_list, "Twin")
             } else {
             Twin_list = c(Twin_list, "None")
             Twin_bool_list = c(Twin_bool_list, "None")
             }
         twin = harmonized_sample_df[harmonized_sample_df$Comb_Name_Tissue == sub("Pre", "Post", exact_name),]
         if (nrow(twin) > 0) {
             Exact_Twin_list = c(Exact_Twin_list, twin$Comb_Name_Tissue[1])
             Exact_Twin_bool_list = c(Exact_Twin_bool_list, "Exact_Twin")
             } else {
             Exact_Twin_list = c(Exact_Twin_list, "None")
             Exact_Twin_bool_list = c(Exact_Twin_bool_list, "None")
             }
        } else if (stage == "PostNACT") {
        twin = harmonized_sample_df[harmonized_sample_df$Comb_Name == sub("Post", "Pre", name),]
        if (nrow(twin) > 0) {
              Twin_list = c(Twin_list, twin$Comb_Name[1])
            Twin_bool_list = c(Twin_bool_list, "Twin")
             } else {
             Twin_list = c(Twin_list, "None")
            Twin_bool_list = c(Twin_bool_list, "None")
             }
         twin = harmonized_sample_df[harmonized_sample_df$Comb_Name_Tissue == sub("Post", "Pre", exact_name),]
         if (nrow(twin) > 0) {
             Exact_Twin_list = c(Exact_Twin_list, twin$Comb_Name_Tissue[1])
             Exact_Twin_bool_list = c(Exact_Twin_bool_list, "Exact_Twin")
             } else {
             Exact_Twin_list = c(Exact_Twin_list, "None")
             Exact_Twin_bool_list = c(Exact_Twin_bool_list, "None")
             }
        } else {
        Twin_list = c(Twin_list, NA)
        Twin_bool_list = c(Twin_bool_list, NA)
        Exact_Twin_list = c(Exact_Twin_list, NA)
        Exact_Twin_bool_list = c(Exact_Twin_bool_list, NA)
        }
    
    
    }
length(Twin_list)
sum
harmonized_sample_df$Twin = Twin_list
harmonized_sample_df$Twin_bool = Twin_bool_list
harmonized_sample_df$Exact_Twin = Exact_Twin_list
harmonized_sample_df$Exact_Twin_bool = Exact_Twin_bool_list

harmonized_sample_df[1:4,]
table(harmonized_sample_df$Twin_bool)
table(harmonized_sample_df$Exact_Twin_bool)

length(unique(harmonized_sample_df[harmonized_sample_df$Twin_bool == "Twin",]$Patient))
length(unique(harmonized_sample_df[harmonized_sample_df$Exact_Twin_bool == "Exact_Twin",]$Patient))

harmonized_sample_twin_df = harmonized_sample_df[harmonized_sample_df$Twin_bool == "Twin",]

722 722 722 722 722 722

 [1] "IDS"             "chemo-naive"     "Treatment-Naive" "Post-NACT"
 [5] "Diagnostic"      "Pre-chemo"       "Interval"        "Post-chemo"
 [9] "Relapse"         NA

[1] 722   8

[1] 722

function (..., na.rm = FALSE)  .Primitive("sum")

  Patient Data_Found_In Assay Tissue  RNAseqID Stage
1 C033    Launonen_2024 Bulk  omentum NA       PostNACT
2 C063    Launonen_2024 Bulk  omentum NA       PostNACT
3 C129    Launonen_2024 Bulk  omentum NA       PostNACT
4 C129    Launonen_2024 Bulk  omentum NA       PostNACT
  Comb_Name_Tissue           Comb_Name          Twin Twin_bool Exact_Twin
1 C033_omentum_PostNACT_Bulk C033_PostNACT_Bulk None None      None
2 C063_omentum_PostNACT_Bulk C063_PostNACT_Bulk None None      None
3 C129_omentum_PostNACT_Bulk C129_PostNACT_Bulk None None      None
4 C129_omentum_PostNACT_Bulk C129_PostNACT_Bulk None None      None
  Exact_Twin_bool
1 None
2 None
3 None
4 None

None Twin
 307  364

Exact_Twin       None
       180        491

[1] 66

[1] 48

In [310]:
table(harmonized_sample_twin_df$Data_Found_In)

Lahtinen_2023 Launonen_2024 Pietilla_2021    Zhang_2022
          185            30            91            58

In [39]:
table(harmonized_patient_prepost_df$Data_Found_In)

                         Lahtinen_2023            Lahtinen_2023;Pietilla_2021
                                    19                                      1
                         Launonen_2024                          Pietilla_2021
                                    15                                      2
                            Zhang_2022               Zhang_2022;Lahtinen_2023
                                     1                                      2
Zhang_2022;Lahtinen_2023;Pietilla_2021               Zhang_2022;Pietilla_2021
                                    23                                      3

In [107]:
# per-patient level data
dim(harmonized_patient_prepost_df)

[1] 66 19

In [108]:
harmonized_patient_prepost_df[1:4,]

  Patient Data_Found_In PlatFI_12_months PlatFI_days FIGO_Stage Tissues
1 S033    Launonen_2024 short            NotinData   IVA        omentum,NA
2 S034    Launonen_2024 short            NotinData   IIIC       omentum,NA
3 S035    Launonen_2024 short            NotinData   IIIC       omentum,NA
4 S036    Launonen_2024 short            NotinData   IIIC       omentum,NA
  Sample_stages   Response_to_Treatment Age       OvaHRDscar BRCAmut_status
1 IDS,chemo-naive NotinData             NotinData HRP        BRCAwt
2 IDS,chemo-naive NotinData             NotinData HRP        BRCAwt
3 IDS,chemo-naive NotinData             NotinData HRP        BRCAwt
4 IDS,chemo-naive NotinData             NotinData HRP        BRCAwt
  CRS       CA125_Uperml_TN_PN Piet21_Survival Piet21Residual_tumor_after_DS
1 NotinData NotinData          NotinData       NotinData
2 NotinData NotinData          NotinData       NotinData
3 NotinData NotinData          NotinData       NotinData
4 NotinData NotinData          NotinData       NotinData
  Piet21_Primary_chemo_regimen Piet21_Progression_free_survival_mths
1 NotinData                    NotinData
2 NotinData                    NotinData
3 NotinData                    NotinData
4 NotinData                    NotinData
  Piet21_Overall_survival_mths Piet21_Relapse_type
1 NotinData                    NotinData
2 NotinData                    NotinData
3 NotinData                    NotinData
4 NotinData                    NotinData

In [110]:
write.table(harmonized_patient_prepost_df, "./EGA_rel_data/Harmonized_EGA_pat_data.txt", quote=FALSE, row.names=FALSE, col.names=TRUE, sep="\t")

## Now get RNAseq EGA labels attached to both

I saved the harmonized data above and then sorted through manually to figure out the list of EGA samples (therefore RNAseq available) with paired Pre and Post (not Relapse) results. This was done in excel (EGA_rel_data/Final_Samples.xlsx). This got us 29 patients. 

Twin is currently alloted only if either there is only one option or if the same tissue is considered.
Final_Bool also indicates the same. If N, then that sample is not included in final analysis (e.g. not paired with Pre/Post but has a corresponding bulk RNA-seq to SC RNA-seq). If NA, then there are multiple options so the one with the greates quality (or multiple) can be used.

In [83]:
ega_meta_samplefile[1:2,]

  sample_accession_id sample_alias
1 EGAN00002747201     EOC1005_pPer1_RNA_seq6
2 EGAN00002747201     EOC1005_pPer1_RNA_seq6
  file_name
1 EOC1005_pPer1_RNA_seq6_V100008511_L3_HK500HUMscnNAAHRAAPEI-509_1.fq.gz
2 EOC1005_pPer1_RNA_seq6_V100008511_L3_HK500HUMscnNAAHRAAPEI-509_2.fq.gz
  file_accession_id
1 EGAF00004723378
2 EGAF00004723379

In [34]:
final_sample_manual <- read_excel("./EGA_rel_data/Final_Samples.xlsx")

final_sample_manual[1:4,]
download_EGAs = ega_meta_samplefile[grepl(paste0(unique(final_sample_manual$Patient), collapse="_|"), ega_meta_samplefile$sample_alias),]
# remove any relapse samples
download_EGAs = download_EGAs[!grepl(paste0(paste0(unique(final_sample_manual$Patient), "_r"), collapse="|"), download_EGAs$sample_alias),]
dim(download_EGAs)
#unique(download_EGAs$file_accession_id)
dim(final_sample_manual)

# save the file accesscian ids as a single file to be read in a bash script
write.table(download_EGAs$file_accession_id, "./EGA_rel_data/Final_Samples_EGAFs.txt", col.names=FALSE, row.names=FALSE, quote=FALSE)

  Patient Final_Bool Assay RNAseqID
1 EOC1005 Y          SC    EOC1005_treatmentNaive_Peritoneum
2 EOC1005 Y          SC    EOC1005_postNACT_Tumor
3 EOC1005 N          Bulk  EOC1005_pPer1_RNA_seq6
4 EOC136  Y          SC    EOC136_treatmentNaive_Mesentery
  Twin                              OG_Tissue  Twin_Tissue Stage Death
1 EOC1005_postNACT_Tumor            Peritoneum Tumor       IVA    0
2 EOC1005_treatmentNaive_Peritoneum Tumor      Peritoneum  NA    NA
3 NA                                Peritoneum NA          NA    NA
4 EOC136_postNACT_Omentum           Mesentery  Omentum     IVA    0
  Res_Tumor_afterPDS Chemo_regimen Therapy_outcome PFS_mth   PFI_days OS_mths
1 1-10 mm            CP-TX-BV      PR               9.133333  896     30
2 NA                 NA            NA                     NA   NA     NA
3 NA                 NA            NA                     NA   NA     NA
4 1-10 mm            CP-TX         CR              23.833333 1006     34
  PFI_daysZhang CRS CA125_Uperml_TN CA125_Uperml_PN Age_Zhang
1  65           2   3776            343             73
2  NA           NA    NA            NA              NA
3  NA           NA    NA            NA              NA
4 520           2   2647            212             64

[1] 324   4

[1] 104  20

In [35]:
length(unique(final_sample_manual$Patient))

sc_pats = final_sample_manual[final_sample_manual$Assay == "SC",]$Patient
bulk_pats = final_sample_manual[final_sample_manual$Assay == "Bulk" & final_sample_manual$Final_Bool != "N",]$Patient

length(intersect(sc_pats, bulk_pats))
length(setdiff(sc_pats, bulk_pats))
length(setdiff(bulk_pats, sc_pats))

[1] 29

[1] 5

[1] 6

[1] 18

29 total patients with 5 patients have SC and Bulk. 6 patients having only SC for paired. 18 patients having both. The SC are found int eh scRNA-seq Perkio data.